#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::doc_markdown,
    clippy::len_zero
)]
//! Conformance suite for the `network` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the
//! model strategy and the injection probes it needs, and asserts that each
//! fixture parses to the exact model it should.
//!
//! `fixtures/network/systemd-261/10-eth0.network` is the stock
//! `systemd-networkd` `.network` shape at systemd 261.3 (sections `[Match]`,
//! `[Network]`, `[Address]`, `[Route]`, `[VLAN]`; `DHCP`, `Address`, `Gateway`,
//! `DNS`, `Destination`, `Id`); the file is verbatim from
//! `man systemd.network`'s example at that tag, trimmed to the modeled subset.
//! `fixtures/network/network-manager-1.52/eth0.nmconnection` is a minimal
//! `NetworkManager` keyfile at `NetworkManager` 1.52
//! (`[connection]`/`[ethernet]`/`[ipv4]`/`[ipv6]`); verbatim from
//! `nm-settings-keyfile(5)` at that tag.
//! `fixtures/network/ifupdown-0.8/interfaces` is Debian's stock
//! `/etc/network/interfaces` at ifupdown 0.8 (stanzas `auto`/`iface` plus
//! `source-directory interfaces.d`); verbatim from the Debian `ifupdown`
//! package at that version.
//! `fixtures/network/netplan-1.1/netplan.yaml` is the stock netplan YAML at
//! netplan 1.1 (`network.ethernets.eth0.{dhcp4,addresses,gateway4,nameservers,routes}`);
//! verbatim from `netplan.io`'s example at that tag.
//! `fixtures/network/edge/` holds hand-made adversarial cases (CRLF, no
//! trailing newline, tabs, unknown sections/keys per backend, YAML
//! comments/anchors left opaque).

use detent_core::descriptor::{HostProfile, ValidationCtx};
use detent_core::module::ConfigModule;
use detent_module_network::{Interface, Model, NetworkModule, Route, Vlan};
use proptest::prelude::{Just, Strategy, prop_oneof};

/// `systemd-networkd` stock `.network` at systemd 261.3.
const SYSTEMD: &str = include_str!("../../../../fixtures/network/systemd-261/10-eth0.network");
/// `NetworkManager` keyfile at `NetworkManager` 1.52.
const NM: &str =
    include_str!("../../../../fixtures/network/network-manager-1.52/eth0.nmconnection");
/// `ifupdown` stock interfaces at ifupdown 0.8.
const IFUPDOWN: &str = include_str!("../../../../fixtures/network/ifupdown-0.8/interfaces");
/// netplan YAML at netplan 1.1.
const NETPLAN: &str = include_str!("../../../../fixtures/network/netplan-1.1/netplan.yaml");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/network/edge/crlf.network");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str =
    include_str!("../../../../fixtures/network/edge/no-trailing-newline.network");
/// Tabs between key and value.
const TABS: &str = include_str!("../../../../fixtures/network/edge/tabs-and-spacing.network");
/// Unknown sections and keys (per-backend) plus YAML anchors/comments left opaque.
const UNKNOWN: &str = include_str!("../../../../fixtures/network/edge/unknown-sections.network");

fn cidr_strategy() -> impl Strategy<Value = String> {
    prop_oneof![
        Just("192.168.1.10/24".to_owned()),
        Just("10.0.0.5/8".to_owned()),
        Just("172.16.0.1/16".to_owned()),
        Just("2001:db8::1/64".to_owned()),
        Just("fd00::1/64".to_owned()),
    ]
}

fn ip_strategy() -> impl Strategy<Value = String> {
    prop_oneof![ip_v4_strategy(), ip_v6_strategy()]
}

fn ip_v4_strategy() -> impl Strategy<Value = String> {
    prop_oneof![
        Just("192.168.1.1".to_owned()),
        Just("8.8.8.8".to_owned()),
        Just("10.0.0.1".to_owned()),
    ]
}

fn ip_v6_strategy() -> impl Strategy<Value = String> {
    // `2001:db8::1` — must contain `:` so a gateway parses back into the
    // same family it was rendered from (invariant 3).
    Just("2001:db8::1".to_owned())
}

fn iface_name_strategy() -> impl Strategy<Value = String> {
    prop_oneof![
        Just("eth0".to_owned()),
        Just("eth1".to_owned()),
        Just("ens3".to_owned()),
        Just("wlan0".to_owned()),
    ]
}

/// A static route whose `via` is in the same family as its `to`.
fn route_strategy() -> impl Strategy<Value = Route> {
    cidr_strategy().prop_flat_map(|to| {
        let via = if to.contains(':') {
            ip_v6_strategy().boxed()
        } else {
            ip_v4_strategy().boxed()
        };
        via.prop_map(move |via| Route {
            to: to.clone(),
            via,
        })
    })
}

fn interface_strategy() -> impl Strategy<Value = Interface> {
    (
        iface_name_strategy(),
        proptest::strategy::Just(false),
        proptest::strategy::Just(false),
        proptest::collection::vec(cidr_strategy(), 0..=2),
        proptest::option::of(ip_v4_strategy()),
        proptest::option::of(ip_v6_strategy()),
        proptest::collection::vec(ip_strategy(), 0..=2),
        proptest::collection::vec(route_strategy(), 0..=2),
        proptest::strategy::Just(None),
        proptest::strategy::Just(None),
    )
        .prop_map(
            |(
                name,
                dhcp_v4,
                dhcp_v6,
                addresses,
                gateway_v4,
                gateway_v6,
                dns,
                routes,
                vlan,
                bridge,
            )| Interface {
                name,
                dhcp_v4,
                dhcp_v6,
                addresses,
                gateway_v4,
                gateway_v6,
                dns,
                routes,
                vlan,
                bridge,
            },
        )
}

fn model_strategy() -> impl Strategy<Value = Model> {
    // 0–3 interfaces with unique names; filter duplicates to keep valid.
    proptest::collection::vec(interface_strategy(), 0..=3).prop_map(|mut ifaces| {
        // Deduplicate by name, keep first occurrence.
        let mut seen = std::collections::BTreeSet::new();
        ifaces.retain(|i| seen.insert(i.name.clone()));
        // `to_model` collects interfaces through a `BTreeMap`, so the read
        // back order is by name; a valid model must match that order for
        // invariant 3 to hold on any backend.
        ifaces.sort_by(|a, b| a.name.cmp(&b.name));
        Model { interfaces: ifaces }
    })
}

fn name_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: value.to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![],
            routes: vec![],
            vlan: None,
            bridge: None,
        }],
    }
}

fn address_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![value.to_owned()],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![],
            routes: vec![],
            vlan: None,
            bridge: None,
        }],
    }
}

fn dns_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![value.to_owned()],
            routes: vec![],
            vlan: None,
            bridge: None,
        }],
    }
}

fn gateway_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec!["192.168.1.10/24".to_owned()],
            gateway_v4: Some(value.to_owned()),
            gateway_v6: None,
            dns: vec![],
            routes: vec![],
            vlan: None,
            bridge: None,
        }],
    }
}

fn route_to_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![],
            routes: vec![Route {
                to: value.to_owned(),
                via: "192.168.1.1".to_owned(),
            }],
            vlan: None,
            bridge: None,
        }],
    }
}

fn route_via_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![],
            routes: vec![Route {
                to: "10.0.0.0/24".to_owned(),
                via: value.to_owned(),
            }],
            vlan: None,
            bridge: None,
        }],
    }
}

fn vlan_link_probe(value: &str) -> Model {
    Model {
        interfaces: vec![Interface {
            name: "eth0".to_owned(),
            dhcp_v4: false,
            dhcp_v6: false,
            addresses: vec![],
            gateway_v4: None,
            gateway_v6: None,
            dns: vec![],
            routes: vec![],
            vlan: Some(Vlan {
                link: value.to_owned(),
                id: 100,
            }),
            bridge: None,
        }],
    }
}

detent_core::module_conformance!(
    NetworkModule,
    fixtures = [
        SYSTEMD, NM, IFUPDOWN, NETPLAN, CRLF, NO_NEWLINE, TABS, UNKNOWN
    ],
    model_strategy = model_strategy(),
    injection_probes = [
        name_probe("a\nb"),
        name_probe("a\rb"),
        name_probe("a\0b"),
        address_probe("a\nb"),
        address_probe("a\0b"),
        dns_probe("a\nb"),
        gateway_probe("a\nb"),
        route_to_probe("a\nb"),
        vlan_link_probe("a\nb"),
        // Characters the upstream syntaxes treat as syntax: `;` and `$()`
        // (shell, via ifupdown's `up` lines), whitespace (argv splitting),
        // `#` (comments), `"` and `[`/`]` (YAML flow and INI headers), `=`.
        route_to_probe("0.0.0.0/0; reboot"),
        route_to_probe("$(reboot)"),
        route_to_probe("10.0.0.0/24 dev eth1"),
        route_to_probe("10.0.0.0/24#x"),
        route_to_probe("\"10.0.0.0/24\""),
        route_to_probe("[10.0.0.0/24]"),
        route_to_probe("to=10.0.0.0/24"),
        route_via_probe("192.168.1.1; reboot"),
        route_via_probe("192.168.1.1 dev eth1"),
        route_via_probe("192.168.1.1#x"),
        route_via_probe("\"192.168.1.1\""),
        route_via_probe("[192.168.1.1]"),
        route_via_probe("via=192.168.1.1"),
        address_probe("192.168.1.10/24 # x"),
        address_probe("[192.168.1.10/24]"),
        dns_probe("8.8.8.8, 1.1.1.1"),
        dns_probe("8.8.8.8 1.1.1.1"),
        gateway_probe("192.168.1.1; reboot"),
        name_probe("eth0:"),
        name_probe("#eth0"),
        vlan_link_probe("eth0 eth1"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [
        SYSTEMD, NM, IFUPDOWN, NETPLAN, CRLF, NO_NEWLINE, TABS, UNKNOWN,
    ] {
        let doc = NetworkModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(NetworkModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed.
fn model_of(src: &str) -> Model {
    NetworkModule::parse(src)
        .ok()
        .and_then(|doc| NetworkModule::to_model(&doc).ok())
        .unwrap_or_default()
}

#[test]
fn systemd_fixture_parses_to_its_interfaces() {
    let model = model_of(SYSTEMD);
    // SYSTEMD has eth0 with DHCP + static address + DNS + route + VLAN
    assert_eq!(model.interfaces.len(), 1);
    let iface = &model.interfaces[0];
    assert_eq!(iface.name, "eth0");
    assert!(iface.dhcp_v4 || iface.dhcp_v6);
    assert!(iface.addresses.iter().any(|a| a == "192.168.1.10/24"));
    assert!(iface.dns.iter().any(|d| d == "192.168.1.1"));
    assert!(!iface.routes.is_empty());
    assert!(iface.vlan.is_some());
}

#[test]
fn nm_fixture_parses_to_its_interfaces() {
    let model = model_of(NM);
    assert_eq!(model.interfaces.len(), 1);
    let iface = &model.interfaces[0];
    assert_eq!(iface.name, "eth0");
    assert!(iface.addresses.iter().any(|a| a == "192.168.1.10/24"));
    assert!(iface.gateway_v4.is_some());
}

#[test]
fn ifupdown_fixture_parses_to_its_interfaces() {
    let model = model_of(IFUPDOWN);
    // lo + eth0
    assert!(model.interfaces.len() >= 1);
    assert!(model.interfaces.iter().any(|i| i.name == "eth0"));
    let eth0 = model.interfaces.iter().find(|i| i.name == "eth0").unwrap();
    assert!(eth0.addresses.iter().any(|a| a == "192.168.1.10/24"));
}

#[test]
fn netplan_fixture_parses_to_its_interfaces() {
    let model = model_of(NETPLAN);
    assert_eq!(model.interfaces.len(), 1);
    let iface = &model.interfaces[0];
    assert_eq!(iface.name, "eth0");
    assert!(iface.addresses.iter().any(|a| a == "192.168.1.10/24"));
    assert_eq!(iface.gateway_v4.as_deref(), Some("192.168.1.1"));
    assert!(!iface.routes.is_empty());
}

#[test]
fn crlf_fixture_parses_without_its_terminators() {
    let model = model_of(CRLF);
    assert_eq!(model.interfaces.len(), 1);
    assert_eq!(model.interfaces[0].name, "eth0");
}

#[test]
fn a_missing_trailing_newline_survives() {
    let model = model_of(NO_NEWLINE);
    assert_eq!(model.interfaces.len(), 1);
    // Round-trip must preserve missing newline.
    let doc = NetworkModule::parse(NO_NEWLINE).unwrap();
    assert_eq!(NetworkModule::render(&doc), NO_NEWLINE);
    assert_eq!(model.interfaces[0].name, "eth0");
}

#[test]
fn tabs_fixture_keeps_the_value_without_its_spacing() {
    let model = model_of(TABS);
    assert_eq!(model.interfaces[0].name, "eth0");
    assert!(
        model.interfaces[0]
            .addresses
            .iter()
            .any(|a| a == "192.168.1.10/24")
    );
}

#[test]
fn unknown_directives_are_not_modeled_but_survive() {
    let model = model_of(UNKNOWN);
    // Unknown sections/keys must not appear as interfaces beyond eth0.
    assert!(model.interfaces.iter().any(|i| i.name == "eth0"));
    // No spurious interface from UnknownSection.
    assert!(!model.interfaces.iter().any(|i| i.name == "UnknownSection"));
    // But the file must still round-trip losslessly (checked above); test that unknown lines exist in render.
    let doc = NetworkModule::parse(UNKNOWN).unwrap();
    let rendered = NetworkModule::render(&doc);
    assert!(rendered.contains("UnknownSection"));
    assert!(rendered.contains("UnknownKey"));
}

/// Static routes traverse the same parse/model/validate/apply/render path as
/// every backend that represents them. NetworkManager is intentionally absent:
/// its modeled keyfile subset has no route representation.
#[test]
fn route_models_validate_and_round_trip_through_real_backends() -> Result<(), String> {
    let sources = [
        "[Match]\nName=eth0\n\n[Route]\nDestination=10.0.0.0/24\nGateway=192.168.1.254\n",
        "auto eth0\niface eth0 inet static\n\tup ip route add 10.0.0.0/24 via 192.168.1.254\n",
        "network:\n  version: 2\n  ethernets:\n    eth0:\n      routes:\n        - to: 10.0.0.0/24\n          via: 192.168.1.254\n",
    ];
    let profile = HostProfile::default_for_tests();
    for source in sources {
        let mut doc = NetworkModule::parse(source).map_err(|e| e.to_string())?;
        let model = NetworkModule::to_model(&doc).map_err(|e| e.to_string())?;
        let route = model
            .interfaces
            .iter()
            .find_map(|iface| iface.routes.first())
            .ok_or_else(|| format!("route missing from parsed model: {model:?}"))?;
        assert_eq!(route.to, "10.0.0.0/24");
        assert_eq!(route.via, "192.168.1.254");
        assert!(!NetworkModule::validate(&model, &ValidationCtx::new(&profile)).has_errors());
        NetworkModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
        let reparsed =
            NetworkModule::parse(&NetworkModule::render(&doc)).map_err(|e| e.to_string())?;
        assert_eq!(
            NetworkModule::to_model(&reparsed).map_err(|e| e.to_string())?,
            model
        );
    }
    Ok(())
}

#[test]
fn an_edited_value_reaches_the_rendered_file() -> Result<(), String> {
    let src = "[Match]\nName=eth0\n\n[Network]\nDHCP=yes\n";
    let mut doc = NetworkModule::parse(src).map_err(|e| e.to_string())?;
    let mut model = NetworkModule::to_model(&doc).map_err(|e| e.to_string())?;
    model.interfaces[0].addresses = vec!["10.0.0.5/24".to_owned()];
    model.interfaces[0].dhcp_v4 = false;
    let report = NetworkModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert!(report.added > 0 || report.changed_lines > 0);
    let rendered = NetworkModule::render(&doc);
    assert!(rendered.contains("10.0.0.5/24"));
    // Unknowns survive: add a comment and ensure edit keeps it.
    let src2 = "# keep me\n[Match]\nName=eth0\n\n[Network]\nDHCP=yes\n";
    let mut doc2 = NetworkModule::parse(src2).map_err(|e| e.to_string())?;
    let mut model2 = NetworkModule::to_model(&doc2).map_err(|e| e.to_string())?;
    model2.interfaces[0].addresses = vec!["10.0.0.5/24".to_owned()];
    model2.interfaces[0].dhcp_v4 = false;
    NetworkModule::apply(&mut doc2, &model2).map_err(|e| e.to_string())?;
    assert!(NetworkModule::render(&doc2).contains("# keep me"));
    Ok(())
}

/// The section header in force at the line that holds `needle`: the last
/// `[...]` line above it.
fn section_above(rendered: &str, needle: &str) -> Option<String> {
    let mut current = None;
    for line in rendered.lines() {
        if line.contains(needle) {
            return current;
        }
        if line.starts_with('[') {
            current = Some(line.to_owned());
        }
    }
    None
}

#[test]
fn edit_keeps_unknown_keys_under_their_section() -> Result<(), String> {
    // H16: `UnknownKey` is not modelled, so it stays where it is. The edit adds
    // a `[Route]` section; that section must not land between `[Network]` and
    // `UnknownKey`, or networkd reads `UnknownKey` as a route key.
    let src = "[Match]\nName=eth0\n\n[UnknownSection]\nFoo=bar\n\n[Network]\nDHCP=yes\nUnknownKey=value\n\n[DHCP]\nRouteMetric=100\n";
    let mut doc = NetworkModule::parse(src).map_err(|e| e.to_string())?;
    let mut model = NetworkModule::to_model(&doc).map_err(|e| e.to_string())?;
    let iface = model
        .interfaces
        .iter_mut()
        .find(|i| i.name == "eth0")
        .ok_or("no eth0 in the model")?;
    iface.dhcp_v4 = false;
    iface.dhcp_v6 = false;
    iface.addresses = vec!["10.0.0.5/24".to_owned()];
    iface.routes = vec![detent_module_network::Route {
        to: "10.1.0.0/16".to_owned(),
        via: "10.0.0.1".to_owned(),
    }];
    NetworkModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    let rendered = NetworkModule::render(&doc);
    assert_eq!(
        section_above(&rendered, "UnknownKey").as_deref(),
        Some("[Network]"),
        "{rendered:?}"
    );
    assert_eq!(
        section_above(&rendered, "Foo=bar").as_deref(),
        Some("[UnknownSection]"),
        "{rendered:?}"
    );
    assert_eq!(
        section_above(&rendered, "RouteMetric").as_deref(),
        Some("[DHCP]"),
        "{rendered:?}"
    );
    let back = NetworkModule::to_model(&doc).map_err(|e| e.to_string())?;
    assert_eq!(back, model);
    Ok(())
}
