//! Conformance suite for the `chrony` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the
//! model strategy and the injection probes it needs, and asserts that each
//! fixture parses to the exact model it should.
//!
//! `fixtures/chrony/chrony-4.9/chrony-default.conf` is the stock Fedora/RHEL
//! `chrony.conf` shape (pools, `makestep`, `rtcsync`, `driftfile`, `logdir`,
//! drop-in directories, comments and blanks); `fixtures/chrony/edge/` holds the
//! hand-made adversarial cases.

use detent_core::module::ConfigModule;
use detent_module_chrony::{ChronyModule, Model, Setting};
use proptest::prelude::Strategy;

/// The stock `chrony.conf` shipped by Fedora/RHEL (chrony 4.9).
const DEFAULT: &str = include_str!("../../../../fixtures/chrony/chrony-4.9/chrony-default.conf");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/chrony/edge/crlf.conf");
/// A file whose last line has no terminator, ending on a valueless directive.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/chrony/edge/no-trailing-newline.conf");
/// Tabs between key and value, hand-aligned columns.
const TABS: &str = include_str!("../../../../fixtures/chrony/edge/tabs-and-spacing.conf");
/// Real directives with no dedicated model, plus a garbage line that is not a
/// directive at all.
const UNKNOWN: &str = include_str!("../../../../fixtures/chrony/edge/unknown-directives.conf");

/// `model_strategy` must generate **valid** models only — values this module's
/// `apply` would refuse make invariants 3 and 4 vacuous, because their checks
/// skip a model that `apply` rejects. Constrain the regexes to what the format
/// really accepts: a key with no whitespace and a value that is already
/// trimmed, non-empty, and free of line breaks.
fn model_strategy() -> impl Strategy<Value = Model> {
    let item =
        ("[a-z][a-z0-9]{0,7}", "[a-z0-9][a-z0-9 ./_-]{0,15}").prop_map(|(key, value)| Setting {
            key,
            value: value.trim().to_owned(),
        });
    proptest::collection::vec(item, 0..=20).prop_map(|settings| Model { settings })
}

/// A model whose value carries `value`, for invariant 5.
fn value_probe(value: &str) -> Model {
    Model {
        settings: vec![Setting {
            key: "makestep".to_owned(),
            value: value.to_owned(),
        }],
    }
}

/// A model whose key carries `value`, for invariant 5.
fn key_probe(value: &str) -> Model {
    Model {
        settings: vec![Setting {
            key: value.to_owned(),
            value: "1 3".to_owned(),
        }],
    }
}

// One probe per field that reaches the rendered line, one per delimiter the
// format uses (`!`, `;`, `#`, `%` open a comment line) as well as `\n`, `\r`
// and NUL. `value_probe("#…")` is deliberately absent: a value starting with
// `#` still round-trips, because chrony has no inline comments — only a line
// that *starts* with a comment character is a comment line.
detent_core::module_conformance!(
    ChronyModule,
    fixtures = [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN],
    model_strategy = model_strategy(),
    injection_probes = [
        value_probe("a\nb"),
        value_probe("a\rb"),
        value_probe("a\0b"),
        key_probe("a\nb"),
        key_probe("a b"),
        key_probe("#makestep"),
        key_probe(";makestep"),
        key_probe("!makestep"),
        key_probe("%makestep"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN] {
        let doc = ChronyModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(ChronyModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so
/// the assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    ChronyModule::parse(src)
        .ok()
        .and_then(|doc| ChronyModule::to_model(&doc).ok())
        .unwrap_or_default()
}

/// Builds an expected setting.
fn expect(key: &str, value: &str) -> Setting {
    Setting {
        key: key.to_owned(),
        value: value.to_owned(),
    }
}

/// One test per fixture, asserting the exact model. A fixture that only
/// round-trips proves losslessness but not that the parser understood it.
#[test]
fn default_fixture_parses_to_its_settings() {
    assert_eq!(
        model_of(DEFAULT),
        Model {
            settings: vec![
                expect("pool", "2.fedora.pool.ntp.org iburst"),
                expect("driftfile", "/var/lib/chrony/drift"),
                expect("makestep", "1 3"),
                expect("rtcsync", ""),
                expect("keyfile", "/etc/chrony.keys"),
                expect("leapsectz", "right/UTC"),
                expect("logdir", "/var/log/chrony"),
                expect("sourcedir", "/etc/chrony/sources.d"),
                expect("confdir", "/etc/chrony/conf.d"),
            ]
        }
    );
}

#[test]
fn crlf_fixture_parses_without_its_terminators() {
    assert_eq!(
        model_of(CRLF),
        Model {
            settings: vec![
                expect("pool", "2.pool.ntp.org iburst"),
                expect("makestep", "1 3"),
                expect("rtcsync", ""),
            ]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            settings: vec![expect("makestep", "1 3"), expect("rtcsync", "")]
        }
    );
}

#[test]
fn tabs_fixture_keeps_the_value_without_its_spacing() {
    assert_eq!(
        model_of(TABS),
        Model {
            settings: vec![
                expect("makestep", "1 3"),
                expect("pool", "2.pool.ntp.org   iburst"),
                expect("rtcsync", ""),
            ]
        }
    );
}

#[test]
fn unknown_directives_are_not_modeled_but_survive() {
    assert_eq!(
        model_of(UNKNOWN),
        Model {
            settings: vec![
                expect("bindaddress", "10.0.0.1"),
                expect("hwtimestamp", "eth0"),
            ]
        }
    );
}

/// The one property the conformance macro cannot express for you — that an
/// edit actually reaches the file, and that everything around it is left
/// alone. A module can satisfy all six invariants by refusing every edit.
#[test]
fn an_edited_value_reaches_the_rendered_file() -> Result<(), String> {
    let src = "# comment\n\nmakestep 1 3\nrtcsync\n# trailing comment\n";
    let mut doc = ChronyModule::parse(src).map_err(|e| e.to_string())?;
    let model = Model {
        settings: vec![expect("makestep", "0 0"), expect("rtcsync", "")],
    };
    let report = ChronyModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert_eq!(report.changed_lines, 1);
    assert_eq!(
        ChronyModule::render(&doc),
        "# comment\n\nmakestep 0 0\nrtcsync\n# trailing comment\n"
    );
    Ok(())
}
