//! `libdetent` — the C ABI for the pure core (PLAN §2.6).
//!
//! This crate exposes a C-callable surface for the registered `ConfigModule`s:
//! `detent_module_list`, `detent_parse`, `detent_render`, `detent_to_model_json`,
//! `detent_apply_json`, `detent_validate_json`, `detent_defaults_json`,
//! `detent_schema_json`, plus `detent_abi_version`, `detent_last_error_message`,
//! and `detent_free`. The header is `include/detent.h`, generated by `cbindgen`
//! from this file (config at `cbindgen.toml`).
//!
//! # Safety
//!
//! No panic ever unwinds across the boundary: the release profile sets
//! `panic = "abort"` (ADR-010), so a bug that panics aborts the host process
//! instead of crossing into C. `catch_unwind` at the boundary was considered
//! and rejected; panics are made structurally impossible via deny-lints plus
//! fuzzing. Every `extern "C"` entry point recovers from allocation failure
//! and user-supplied UTF-8 / JSON shape errors, routing them to a
//! thread-local last-error buffer readable through
//! `detent_last_error_message()`. The `unsafe_code` deny lint forbids code paths
//! that need raw pointers; the few we do (allocating tagged buffers, registering
//! documents) are confined to items annotated with `#[allow(unsafe_code)]` and
//! a `// SAFETY:` comment justifying the invariant.
//!
//! # ABI versioning
//!
//! `detent_abi_version()` returns the integer compiled into the library. The
//! header pins the same constant as `DETENT_ABI_VERSION`. Bumping it is a
//! SONAME bump (PLAN §2.6, `libdetent.so.0`).
//!
//! # Pointer discipline
//!
//! Every pointer this library hands back to C is tagged with an
//! [`AllocHeader`] directly preceding the user-visible byte. That header
//! tells `detent_free` whether to drop a `String` or a doc-handle slot, and
//! `detent_free` refuses to touch a foreign or already-freed pointer
//! (`MAGIC_STRING`/`MAGIC_DOC` mismatch = silent leak on the caller).
#![deny(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![warn(missing_docs)]

use std::alloc::{Layout, alloc, dealloc};
use std::cell::Cell;
use std::collections::BTreeMap;
use std::collections::HashSet;
use std::ffi::CString;
use std::os::raw::c_char;
use std::sync::{Arc, LazyLock, Mutex};

use detent_core::descriptor::{HostProfile, InitSystem, Os, ValidationCtx};
use detent_core::module::DynModule;
use detent_modules::modules;
use serde_json::Value;

/// The ABI version this build exposes. Bumping requires a SONAME bump.
pub const DETENT_ABI_VERSION: u32 = 0;

/// C-visible success.
pub const DETENT_OK: i32 = 0;
/// A required pointer argument was NULL.
pub const DETENT_ERR_NULL_ARGUMENT: i32 = 1;
/// A byte slice was not valid UTF-8.
pub const DETENT_ERR_INVALID_UTF8: i32 = 2;
/// The requested `module_id` is not in the registry.
pub const DETENT_ERR_UNKNOWN_MODULE: i32 = 3;
/// `ConfigModule::parse` rejected the input.
pub const DETENT_ERR_PARSE: i32 = 4;
/// A model JSON could not be deserialized, or a document could not be projected.
pub const DETENT_ERR_MODEL: i32 = 5;
/// `ConfigModule::apply` rejected the edit.
pub const DETENT_ERR_EDIT: i32 = 6;
/// A JSON input was syntactically invalid.
pub const DETENT_ERR_INVALID_JSON: i32 = 7;
/// Allocation failed or an internal invariant was violated.
pub const DETENT_ERR_INTERNAL: i32 = 8;

// ------------------------------------------------------------------------ header

/// Magic numbers that tag the layout written immediately before every pointer
/// returned to C. `detent_free` reads them to decide whether to drop a
/// `String` or a `Box<DocHandle>`, then deallocates the whole slab. Using two
/// distinct values means a stray `detent_free` on a foreign pointer is
/// detectable — and the check is on the call site rather than across the
/// allocator boundary.
const MAGIC_STRING: u32 = 0xDE_5E_11_A0;
const MAGIC_DOC: u32 = 0xDE_5E_11_D0;

#[repr(C)]
#[derive(Clone, Copy)]
struct AllocHeader {
    magic: u32,
    /// Doc: the index of the handle in the global table. String: unused (0).
    index: u64,
    /// String: the user-visible byte length (excluding the trailing NUL).
    /// Doc: unused (0).
    len: u64,
}

const HEADER_LEN: usize = std::mem::size_of::<AllocHeader>();

/// Layout used for every allocation handed to C.
///
/// The alignment is `usize` so the header's `u32`/`u64` fields stay naturally
/// aligned on every supported target — no UB if a C consumer reads the header
/// bytes back. A doc handle stores zero payload bytes; the tagged pointer is
/// the entire object.
fn alloc_layout(payload_len: usize) -> Result<Layout, ()> {
    let total = HEADER_LEN.checked_add(payload_len).ok_or(())?;
    Layout::from_size_align(total, std::mem::align_of::<usize>()).map_err(|_| ())
}

/// Writes `header` into the bytes at `raw`.
///
/// Field-by-field writes avoid `clippy::cast_ptr_alignment`: each field's
/// alignment is naturally satisfied because the allocator returned a
/// `usize`-aligned pointer and the struct is `repr(C)` so field offsets are
/// stable. The caller is responsible for the write being exclusively theirs.
#[allow(unsafe_code, clippy::cast_ptr_alignment)]
fn write_header(raw: *mut u8, header: AllocHeader) {
    // SAFETY: `raw` is exclusively ours and at least `HEADER_LEN` bytes of
    // writable memory. Each field offset is properly aligned.
    unsafe {
        raw.cast::<u32>().write(header.magic);
        raw.add(8).cast::<u64>().write(header.index);
        raw.add(16).cast::<u64>().write(header.len);
    }
}

/// Reads `header` from the bytes at `raw`.
///
/// Field-by-field reads avoid `clippy::cast_ptr_alignment` for the same
/// reason as [`write_header`].
#[allow(unsafe_code, clippy::cast_ptr_alignment)]
fn read_header(raw: *const u8) -> AllocHeader {
    // SAFETY: `raw` is at least `HEADER_LEN` bytes of readable memory; each
    // field read lands on its natural alignment.
    unsafe {
        AllocHeader {
            magic: raw.cast::<u32>().read(),
            index: raw.add(8).cast::<u64>().read(),
            len: raw.add(16).cast::<u64>().read(),
        }
    }
}

/// Allocates a tagged block from the system allocator.
///
/// `payload_len` is the number of bytes following the header; pass `0` for a
/// doc handle. The caller must write the payload (when non-empty) and return
/// `payload_ptr + HEADER_LEN` to C.
#[allow(unsafe_code)]
fn alloc_block(payload_len: usize, header: AllocHeader) -> Option<*mut u8> {
    let layout = alloc_layout(payload_len).ok()?;
    // SAFETY: layout is sized correctly; `alloc` returns a suitably aligned
    // heap pointer. We then write the tag header in place.
    let raw = unsafe { alloc(layout) };
    if raw.is_null() {
        return None;
    }
    write_header(raw, header);
    // SAFETY: `HEADER_LEN` is in range of the allocation; the offset pointer
    // is what we hand to C.
    unsafe { Some(raw.add(HEADER_LEN)) }
}

/// Allocates a tagged string block and returns its payload pointer.
///
/// The returned `*mut c_char` is NUL-terminated by `CString`, so any C code
/// can treat it as a plain `const char *`. Freeing is via `detent_free`.
#[allow(unsafe_code)]
fn alloc_cstring(s: String) -> *mut c_char {
    let Ok(cstring) = CString::new(s) else {
        return std::ptr::null_mut();
    };
    let bytes = cstring.into_bytes_with_nul();
    let payload_len = bytes.len();
    let user_len = payload_len.saturating_sub(1);
    // SAFETY: alloc_block gives us a valid pointer; we copy `bytes` into
    // the payload region and hand the offset pointer to C.
    let Some(raw) = alloc_block(
        payload_len,
        AllocHeader {
            magic: MAGIC_STRING,
            index: 0,
            len: user_len as u64,
        },
    ) else {
        return std::ptr::null_mut();
    };
    // SAFETY: `raw` is the offset pointer; payload_len bytes are writable.
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), raw, payload_len);
    }
    let out = raw.cast::<c_char>();
    track(out);
    out
}

// ------------------------------------------------------------- document handle

/// A parsed document, kept opaque across the ABI boundary.
///
/// Storing the source text plus the module's `Arc<dyn DynModule>` keeps the
/// type-generic FFI from naming any particular module's `Doc`. Render and
/// `to_model_json` re-parse on demand; for the formats this library targets
/// (line-oriented, ≤ a few thousand lines) the cost is negligible compared
/// to the JSON serialization that follows.
struct DocHandle {
    module: Arc<dyn DynModule>,
    /// The exact bytes the caller handed us, including a possible trailing
    /// `\n`. Stored as `String` so it round-trips back into `render` byte for
    /// byte — that is what invariant 4 (`render(parse(s)) == s`) buys us.
    source: String,
}

/// Payload pointers this library handed to C and has not freed.
///
/// `detent_free` and `split_doc` consult this set *before* forming
/// `ptr - HEADER_LEN`: reading a header through a foreign pointer is UB even
/// when the magic then mismatches (Miri rejects the `sub` itself), so set
/// membership — not the magic — is the foreign-pointer gate. The magic still
/// discriminates string vs doc among members. Stored as `usize` addresses,
/// only compared, never dereferenced; the original pointer (with its
/// provenance) is what gets read after a membership hit.
static LIVE: LazyLock<Mutex<HashSet<usize>>> = LazyLock::new(|| Mutex::new(HashSet::new()));

/// Records a payload pointer handed to C. Best-effort under lock poisoning:
/// a missed insert risks a later spurious "unknown" refusal, never unsoundness.
fn track(ptr: *mut c_char) {
    if let Ok(mut live) = LIVE.lock() {
        live.insert(ptr as usize);
    }
}

/// Removes `ptr`, returning whether it was a live hand-out. Foreign pointers
/// and double frees read `false` and must not be touched.
fn untrack(ptr: *mut c_char) -> bool {
    LIVE.lock()
        .is_ok_and(|mut live| live.remove(&(ptr as usize)))
}

/// Whether `ptr` is a live hand-out, without removing it. For `split_doc`,
/// which borrows rather than frees.
fn is_live(ptr: *const c_char) -> bool {
    LIVE.lock().is_ok_and(|live| live.contains(&(ptr as usize)))
}

/// Global table of live document handles. The `usize` keys are also written
/// into `AllocHeader.index` so `detent_free` knows which slot to drop.
static DOC_HANDLES: LazyLock<Mutex<BTreeMap<usize, Box<DocHandle>>>> =
    LazyLock::new(|| Mutex::new(BTreeMap::new()));

/// Reserves a fresh handle id. 0 is reserved for "no handle", matching the
/// error convention used in C.
fn next_handle_id(table: &mut BTreeMap<usize, Box<DocHandle>>) -> usize {
    let mut id = 1usize;
    while table.contains_key(&id) {
        // Ponytail: a linear scan is fine; the table is small and only grows
        // on the rare path of long-lived C clients. Switch to a free-list
        // when a benchmark shows contention.
        id = id.saturating_add(1);
        if id == usize::MAX {
            return 0;
        }
    }
    id
}

// --------------------------------------------------------------------- registry

/// A snapshot of the modules this build was compiled with.
struct Registry {
    by_id: BTreeMap<String, Arc<dyn DynModule>>,
    ids: Vec<&'static str>,
}

fn registry() -> &'static Registry {
    static CACHE: LazyLock<Registry> = LazyLock::new(|| {
        let mut by_id = BTreeMap::new();
        let mut ids = Vec::new();
        for m in modules() {
            let id: &'static str = m.id();
            ids.push(id);
            // `Arc<dyn DynModule>` so the same `Registry` entry can sit in
            // many `DocHandle`s without a clone cost on the heap object.
            by_id.insert(id.to_owned(), Arc::from(m));
        }
        Registry { by_id, ids }
    });
    &CACHE
}

fn lookup_module(id: &str) -> Option<Arc<dyn DynModule>> {
    registry().by_id.get(id).cloned()
}

// ------------------------------------------------------------- last-error slot

thread_local! {
    /// The most recent error message on this thread: a private tagged-block
    /// hand-out plus its payload length, or `(null, 0)` when the last call
    /// succeeded. `detent_last_error_message` returns a borrow of that
    /// allocation, valid until the next FFI call on this thread replaces or
    /// clears the slot; copy if you need to keep it. The buffer is
    /// deliberately *not* in the `LIVE` hand-out set, so a caller that
    /// (against the docs) passes it to `detent_free` is refused before any
    /// header read and the slot never dangles. A raw pointer — not a
    /// `Cell<Option<CString>>` — is the only thing that survives here: taking
    /// the `CString` out and putting it back frees and re-protects the buffer
    /// on `set`, which is exactly the use-after-free Miri caught
    /// (`Cell::take` + `as_ptr` + `Cell::set` invalidates the tag the returned
    /// pointer was derived from).
    ///
    /// `LastErrorSlot`'s `Drop` frees the buffer at thread exit, so no leak
    /// is reported for threads that end with an error still set.
    static LAST_ERROR: LastErrorSlot = const { LastErrorSlot::new() };
}

/// Owning holder for the thread-local last-error buffer (see `LAST_ERROR`).
struct LastErrorSlot(Cell<(*const c_char, usize)>);

impl LastErrorSlot {
    const fn new() -> Self {
        Self(Cell::new((std::ptr::null(), 0)))
    }

    fn replace(&self, ptr: *const c_char, len: usize) -> (*const c_char, usize) {
        let old = self.0.get();
        self.0.set((ptr, len));
        old
    }

    fn get(&self) -> (*const c_char, usize) {
        self.0.get()
    }
}

#[allow(unsafe_code)]
impl Drop for LastErrorSlot {
    fn drop(&mut self) {
        let (ptr, len) = self.0.get();
        if !ptr.is_null() {
            // SAFETY: `ptr`/`len` are exactly what an earlier `set_last_error`
            // installed and were never handed out, so `free_slot_buffer`'s
            // contract holds; `Drop` runs once at thread exit.
            unsafe { free_slot_buffer(ptr, len) };
        }
    }
}

/// Frees a buffer previously installed in `LAST_ERROR` by `set_last_error`.
///
/// # Safety
///
/// `ptr`/`len` must be exactly what an earlier `set_last_error` installed:
/// an `alloc_block` payload of `len` bytes, touched only by this slot (it is
/// untracked, so `detent_free` refuses it), hence exclusive and correctly
/// sized.
#[allow(unsafe_code)]
unsafe fn free_slot_buffer(ptr: *const c_char, len: usize) {
    // SAFETY: by the `LAST_ERROR` ownership argument above.
    unsafe {
        if let Ok(layout) = alloc_layout(len) {
            dealloc(ptr.cast_mut().cast::<u8>().sub(HEADER_LEN), layout);
        }
    }
}

/// Installs `msg` as the current thread's last error, NUL-terminated, freeing
/// the previous buffer if any. Never fails: a message with an interior NUL
/// falls back to a static, and an allocation failure keeps the previous
/// message, so the error path itself cannot error or panic.
#[allow(unsafe_code)]
fn set_last_error(msg: impl Into<String>) {
    let s: String = msg.into();
    let cstr = CString::new(s).unwrap_or(c"internal: error text had NUL".into());
    let bytes = cstr.into_bytes_with_nul();
    let payload_len = bytes.len();
    // SAFETY: fresh `alloc_block` output; the payload region is writable and
    // large enough for `bytes` by construction of the layout.
    let Some(dst) = alloc_block(
        payload_len,
        AllocHeader {
            magic: MAGIC_STRING,
            index: 0,
            len: payload_len.saturating_sub(1) as u64,
        },
    ) else {
        return;
    };
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), dst, payload_len);
    }
    let ptr = dst.cast::<c_char>();
    LAST_ERROR.with(|slot| {
        let (old, old_len) = slot.replace(ptr.cast_const(), payload_len);
        if !old.is_null() {
            // SAFETY: `old` came from this slot, i.e. an earlier
            // `alloc_block` of exactly `old_len` payload bytes; only this
            // slot ever touches it (it is untracked, so `detent_free`
            // refuses it) — exactly what `free_slot_buffer` requires.
            unsafe { free_slot_buffer(old, old_len) };
        }
    });
}

#[allow(unsafe_code)]
fn clear_last_error() {
    LAST_ERROR.with(|slot| {
        let (old, old_len) = slot.replace(std::ptr::null(), 0);
        if !old.is_null() {
            // SAFETY: same slot-owned hand-out argument as in `set_last_error`.
            unsafe { free_slot_buffer(old, old_len) };
        }
    });
}

fn last_error_ptr() -> *const c_char {
    LAST_ERROR.with(|slot| slot.get().0)
}

// -------------------------------------------------------------------- helpers

/// Validates that `ptr` is not null and that `len` bytes form UTF-8.
#[allow(unsafe_code)]
fn check_utf8<'a>(ptr: *const c_char, len: usize, what: &str) -> Result<&'a str, i32> {
    if ptr.is_null() {
        set_last_error(format!("{what} is NULL"));
        return Err(DETENT_ERR_NULL_ARGUMENT);
    }
    // SAFETY: caller guarantees the bytes are readable for `len`.
    let bytes = unsafe { std::slice::from_raw_parts(ptr.cast::<u8>(), len) };
    match std::str::from_utf8(bytes) {
        Ok(s) => Ok(s),
        Err(e) => {
            set_last_error(format!("{what} is not valid UTF-8: {e}"));
            Err(DETENT_ERR_INVALID_UTF8)
        }
    }
}

/// Builds a `HostProfile` from the small set of fields C can express.
fn make_profile(os_id: u8, init_id: u8, hostname: String, ram_mib: u64) -> HostProfile {
    HostProfile {
        os: os_from_id(os_id),
        init: init_from_id(init_id),
        hostname,
        service_versions: BTreeMap::new(),
        ram_mib,
    }
}

// ------------------------------------------------------------------------ FFI
//
// Each `extern "C"` entry point carries `#[allow(unsafe_code)]` for the
// `#[unsafe(no_mangle)]` attribute (Rust 2024) and the small number of
// pointer-touching operations inside. The `// SAFETY:` comment names the
// invariant being upheld for each `unsafe { ... }`.

/// Returns the ABI version this build was compiled with.
///
/// Bumped in lockstep with `DETENT_ABI_VERSION` in `include/detent.h`. Any
/// mismatch is a SONAME mismatch and the library should not be loaded.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_abi_version() -> u32 {
    DETENT_ABI_VERSION
}

/// Returns the message of the last error raised on this thread, or NULL when
/// the most recent call on this thread succeeded.
///
/// The pointer is a borrow of the thread-local error slot: **any** later FFI
/// call on this thread invalidates it — including successful calls, which
/// clear the slot on entry — and may free the underlying buffer. Copy the
/// string immediately if you need to retain it.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_last_error_message() -> *const c_char {
    last_error_ptr()
}

/// Lists the module ids this build was compiled with, as a JSON array of
/// strings (e.g. `["hosts","resolver"]`). The returned buffer is owned by
/// libdetent — release it with `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_module_list() -> *mut c_char {
    clear_last_error();
    let ids = &registry().ids;
    let json = match serde_json::to_string(ids) {
        Ok(s) => s,
        Err(e) => {
            set_last_error(format!("internal: cannot serialize module list: {e}"));
            return std::ptr::null_mut();
        }
    };
    alloc_cstring(json)
}

/// Parses `src` with the module identified by `module_id` and returns a
/// document handle. The handle must be released with `detent_free`. Returns
/// NULL on error; the code is in `detent_last_error_message()`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_parse(
    module_id: *const c_char,
    src: *const c_char,
    src_len: usize,
) -> *mut c_char {
    clear_last_error();
    let module_id = match check_utf8(module_id, libc_strlen(module_id), "module_id") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let src_str = match check_utf8(src, src_len, "src") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let Some(module) = lookup_module(&module_id) else {
        set_last_error(format!("unknown module id `{module_id}`"));
        return std::ptr::null_mut();
    };
    let Ok(layout) = alloc_layout(0) else {
        set_last_error("internal: allocation layout overflowed".to_owned());
        return std::ptr::null_mut();
    };
    // SAFETY: see `alloc_block`. Doc handles carry no payload.
    let raw = unsafe { alloc(layout) };
    if raw.is_null() {
        set_last_error("internal: allocation failed".to_owned());
        return std::ptr::null_mut();
    }
    let Ok(mut t) = DOC_HANDLES.lock() else {
        set_last_error("internal: handle table poisoned".to_owned());
        // SAFETY: same `raw` from `alloc(layout)`.
        unsafe { dealloc(raw, layout) };
        return std::ptr::null_mut();
    };
    let id = next_handle_id(&mut t);
    if id == 0 {
        drop(t);
        set_last_error("internal: handle table exhausted".to_owned());
        // SAFETY: `raw` came from `alloc` with `layout` above.
        unsafe { dealloc(raw, layout) };
        return std::ptr::null_mut();
    }
    t.insert(
        id,
        Box::new(DocHandle {
            module,
            source: src_str,
        }),
    );
    let idx = id;
    write_header(
        raw,
        AllocHeader {
            magic: MAGIC_DOC,
            index: idx as u64,
            len: 0,
        },
    );
    // SAFETY: `HEADER_LEN` is in range; the offset pointer is what C sees.
    let out = unsafe { raw.add(HEADER_LEN).cast::<c_char>() };
    track(out);
    out
}

/// Renders a document back to text such that `render(parse(src)) == src`.
///
/// Returns a malloced NUL-terminated buffer, or NULL on error. Release the
/// success return with `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_render(doc: *mut c_char) -> *mut c_char {
    clear_last_error();
    let Ok((module, source)) = split_doc(doc) else {
        return std::ptr::null_mut();
    };
    // `render(parse(s)) == s` is invariant 4. We force it by going through
    // `parse_to_model_json` + `apply_json(model)`: that is the round-trip
    // every module guarantees, and `apply_json` has no side effects on the
    // module state.
    let json = match module.parse_to_model_json(&source) {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("parse failed: {e}"));
            return std::ptr::null_mut();
        }
    };
    match module.apply_json(&source, &json) {
        Ok(s) => alloc_cstring(s),
        Err(e) => {
            set_last_error(format!("render failed: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Projects a document onto its typed model, returning the model as JSON.
/// Release the buffer with `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_to_model_json(doc: *mut c_char) -> *mut c_char {
    clear_last_error();
    let Ok((module, source)) = split_doc(doc) else {
        return std::ptr::null_mut();
    };
    match module.parse_to_model_json(&source) {
        Ok(v) => match serde_json::to_string(&v) {
            Ok(s) => alloc_cstring(s),
            Err(e) => {
                set_last_error(format!("internal: cannot serialize model: {e}"));
                std::ptr::null_mut()
            }
        },
        Err(e) => {
            set_last_error(format!("to_model failed: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Applies `model_json` to `src` via the module and returns the rendered
/// text. Stateless: release every successful return with `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_apply_json(
    module_id: *const c_char,
    src: *const c_char,
    src_len: usize,
    model_json: *const c_char,
    model_len: usize,
) -> *mut c_char {
    clear_last_error();
    let module_id = match check_utf8(module_id, libc_strlen(module_id), "module_id") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let src_str = match check_utf8(src, src_len, "src") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let model_json_str = match check_utf8(model_json, model_len, "model_json") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let Some(module) = lookup_module(&module_id) else {
        set_last_error(format!("unknown module id `{module_id}`"));
        return std::ptr::null_mut();
    };
    let model: Value = match serde_json::from_str(&model_json_str) {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("model_json is not valid JSON: {e}"));
            return std::ptr::null_mut();
        }
    };
    match module.apply_json(&src_str, &model) {
        Ok(s) => alloc_cstring(s),
        Err(e) => {
            set_last_error(format!("apply failed: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Validates a model JSON against the module's schema plus its
/// `ConfigModule::validate` checks. Returns the diagnostics as a JSON array
/// (matching `detent_core::diag::Diagnostics`'s serialization). Release with
/// `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_validate_json(
    module_id: *const c_char,
    model_json: *const c_char,
    model_len: usize,
    os_id: u8,
    init_id: u8,
    hostname: *const c_char,
    hostname_len: usize,
    ram_mib: u64,
) -> *mut c_char {
    clear_last_error();
    let module_id = match check_utf8(module_id, libc_strlen(module_id), "module_id") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let model_json_str = match check_utf8(model_json, model_len, "model_json") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let model_value: Value = match serde_json::from_str(&model_json_str) {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("model_json is not valid JSON: {e}"));
            return std::ptr::null_mut();
        }
    };
    let hostname_str = match check_utf8(hostname, hostname_len, "hostname") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let Some(module) = lookup_module(&module_id) else {
        set_last_error(format!("unknown module id `{module_id}`"));
        return std::ptr::null_mut();
    };
    let profile = make_profile(os_id, init_id, hostname_str, ram_mib);
    let ctx = ValidationCtx::new(&profile);
    match module.validate_json(&model_value, &ctx) {
        Ok(diags) => match serde_json::to_string(&diags) {
            Ok(s) => alloc_cstring(s),
            Err(e) => {
                set_last_error(format!("internal: cannot serialize diagnostics: {e}"));
                std::ptr::null_mut()
            }
        },
        Err(e) => {
            set_last_error(format!("validate failed: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Returns the module's host-appropriate defaults as a JSON value matching
/// its model schema. `profile_json` is a `HostProfile`-shaped JSON object;
/// fields fall back to `Default::default()` when omitted.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_defaults_json(
    module_id: *const c_char,
    profile_json: *const c_char,
    profile_len: usize,
) -> *mut c_char {
    clear_last_error();
    let module_id = match check_utf8(module_id, libc_strlen(module_id), "module_id") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let Ok(profile_str) = check_utf8(profile_json, profile_len, "profile_json") else {
        return std::ptr::null_mut();
    };
    let Some(module) = lookup_module(&module_id) else {
        set_last_error(format!("unknown module id `{module_id}`"));
        return std::ptr::null_mut();
    };
    let profile: HostProfile = serde_json::from_str(profile_str).unwrap_or_default();
    match module.defaults_json(&profile) {
        Ok(v) => match serde_json::to_string(&v) {
            Ok(s) => alloc_cstring(s),
            Err(e) => {
                set_last_error(format!("internal: cannot serialize defaults: {e}"));
                std::ptr::null_mut()
            }
        },
        Err(e) => {
            set_last_error(format!("defaults failed: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Returns the module's model schema as a JSON Schema document, including
/// any `x-detent` UI hints the module attaches. Release with `detent_free`.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn detent_schema_json(module_id: *const c_char) -> *mut c_char {
    clear_last_error();
    let module_id = match check_utf8(module_id, libc_strlen(module_id), "module_id") {
        Ok(s) => s.to_owned(),
        Err(_) => return std::ptr::null_mut(),
    };
    let Some(module) = lookup_module(&module_id) else {
        set_last_error(format!("unknown module id `{module_id}`"));
        return std::ptr::null_mut();
    };
    let schema = module.schema_json();
    match serde_json::to_string(&schema) {
        Ok(s) => alloc_cstring(s),
        Err(e) => {
            set_last_error(format!("internal: cannot serialize schema: {e}"));
            std::ptr::null_mut()
        }
    }
}

/// Frees any buffer or handle returned by this library. A `NULL` argument is
/// a no-op (matching `free(3)`).
///
/// Passing a foreign pointer is safe (untracked hand-outs are refused before
/// any header read, and the pointer is left alone) but the buffer it points
/// at will leak. Passing an already-freed pointer is likewise refused: the
/// hand-out is removed from the set on free, so a second free reads `false`
/// and touches nothing (the first free's memory may already be reused).
///
/// # Safety
///
/// `ptr` must be either NULL or a pointer previously returned by a function
/// in this library (one of `detent_module_list`, `detent_parse`,
/// `detent_render`, `detent_to_model_json`, `detent_apply_json`,
/// `detent_validate_json`, `detent_defaults_json`, `detent_schema_json`).
/// Any other pointer is safely ignored but leaks relative to us.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn detent_free(ptr: *mut c_char) {
    if ptr.is_null() {
        return;
    }
    // Membership in the hand-out set — not the magic — gates every header
    // read below: `ptr.sub(HEADER_LEN)` on a foreign pointer is UB even when
    // the magic would then mismatch, because Miri rejects the `sub` itself.
    // The original pointer (with its provenance) is what gets read after a
    // membership hit, so no integer-to-pointer round trip ever occurs.
    if !untrack(ptr) {
        return;
    }
    // SAFETY: `ptr` is a live hand-out of ours, so `HEADER_LEN` bytes before
    // it are our readable header; we dealloc only after the magic matches.
    unsafe {
        let raw = ptr.sub(HEADER_LEN).cast::<u8>();
        let header = read_header(raw);
        match header.magic {
            MAGIC_STRING => {
                let payload_len = match usize::try_from(header.len) {
                    Ok(n) => n.saturating_add(1),
                    Err(_) => 0,
                };
                if let Ok(layout) = alloc_layout(payload_len) {
                    dealloc(raw, layout);
                }
            }
            MAGIC_DOC => {
                if let (Ok(idx), Ok(mut table)) =
                    (usize::try_from(header.index), DOC_HANDLES.lock())
                {
                    table.remove(&idx);
                }
                if let Ok(layout) = alloc_layout(0) {
                    dealloc(raw, layout);
                }
            }
            _ => {}
        }
    }
}

// ------------------------------------------------------------ helpers (file)

/// Reads the tag header at `ptr-HEADER_LEN` and returns the `(module, source)`
/// pair, or an error code.
#[allow(unsafe_code)]
fn split_doc(doc: *mut c_char) -> Result<(Arc<dyn DynModule>, String), i32> {
    if doc.is_null() {
        set_last_error("document handle is NULL".to_owned());
        return Err(DETENT_ERR_NULL_ARGUMENT);
    }
    if !is_live(doc) {
        set_last_error("document handle is unknown (foreign or already freed?)".to_owned());
        return Err(DETENT_ERR_NULL_ARGUMENT);
    }
    // SAFETY: `doc` is a live hand-out from `detent_parse`, whose header sits
    // exactly `HEADER_LEN` bytes before the user pointer.
    let header = unsafe { read_header(doc.sub(HEADER_LEN).cast::<u8>()) };
    if header.magic != MAGIC_DOC {
        set_last_error("document handle has the wrong tag".to_owned());
        return Err(DETENT_ERR_NULL_ARGUMENT);
    }
    let Ok(idx) = usize::try_from(header.index) else {
        set_last_error("document handle index is out of range".to_owned());
        return Err(DETENT_ERR_INTERNAL);
    };
    let table = DOC_HANDLES.lock();
    let Ok(t) = table else {
        set_last_error("internal: handle table poisoned".to_owned());
        return Err(DETENT_ERR_INTERNAL);
    };
    let Some(handle) = t.get(&idx) else {
        set_last_error("document handle is unknown (already freed?)".to_owned());
        return Err(DETENT_ERR_NULL_ARGUMENT);
    };
    Ok((handle.module.clone(), handle.source.clone()))
}

/// Reads the C strlen of a NUL-terminated string from a C pointer.
///
/// The pointer is required to be non-null; the terminator must exist within
/// the addressable region. We never dereference past it.
#[allow(unsafe_code)]
fn libc_strlen(ptr: *const c_char) -> usize {
    if ptr.is_null() {
        return 0;
    }
    let mut n = 0usize;
    // SAFETY: stops at the first NUL. C strings returned by the caller are
    // terminated or this FFI is already unsound.
    unsafe {
        while *ptr.add(n) != 0 {
            n = n.saturating_add(1);
        }
    }
    n
}

const fn os_from_id(id: u8) -> Os {
    match id {
        0 => Os::Linux,
        1 => Os::MacOs,
        _ => Os::Other,
    }
}

const fn init_from_id(id: u8) -> InitSystem {
    match id {
        1 => InitSystem::Systemd,
        2 => InitSystem::OpenRc,
        3 => InitSystem::Launchd,
        _ => InitSystem::None,
    }
}
