//! Conformance suite for the `TEMPLATE` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.
//!
//! TODO(fixtures): replace the inline `const`s below with real upstream samples:
//!
//! ```ignore
//! const DEFAULT: &str = include_str!("../../../../fixtures/TEMPLATE/TEMPLATE-0.0/default.conf");
//! ```
//!
//! The template ships them inline only so that a fresh copy compiles before its
//! `fixtures/<id>/` directory exists. A module whose fixtures are hand-written
//! text is not covered by Appendix A: the point of a fixture is that upstream, not
//! the module author, chose its formatting.

use detent_core::module::ConfigModule;
use detent_module_TEMPLATE::{Model, Setting, TemplateModule};
use proptest::prelude::Strategy;

/// A stock file: comments, blanks, and settings.
const DEFAULT: &str = "# /etc/TEMPLATE.conf\n\nmode strict\nbackend systemd\n";
/// Hand-aligned columns and a directive this module does not model.
const ALIGNED: &str = "mode        strict\nbackend     systemd\nunknown-flag\n";
/// Every line terminated with `\r\n`.
const CRLF: &str = "mode strict\r\nbackend systemd\r\n";
/// A file whose last line has no terminator.
const NO_NEWLINE: &str = "mode strict\nbackend systemd";

/// TODO(strategy): `model_strategy` must generate **valid** models only — values
/// this module's `apply` would refuse make invariants 3 and 4 vacuous, because
/// their checks skip a model that `apply` rejects. Constrain the regexes to what
/// the format really accepts; here that is a key with no whitespace and a value
/// that is already trimmed and non-empty.
fn model_strategy() -> impl Strategy<Value = Model> {
    let item =
        ("[a-z][a-z0-9-]{0,7}", "[a-z0-9][a-z0-9 ]{0,9}[a-z0-9]").prop_map(|(key, value)| {
            Setting {
                key,
                value: value.trim().to_owned(),
            }
        });
    proptest::collection::vec(item, 0..=20).prop_map(|settings| Model { settings })
}

/// A model whose value carries `value`, for invariant 5.
fn value_probe(value: &str) -> Model {
    Model {
        settings: vec![Setting {
            key: "mode".to_owned(),
            value: value.to_owned(),
        }],
    }
}

/// A model whose key carries `value`, for invariant 5.
fn key_probe(value: &str) -> Model {
    Model {
        settings: vec![Setting {
            key: value.to_owned(),
            value: "strict".to_owned(),
        }],
    }
}

// TODO(conformance): the macro parameters are documented on
// `detent_core::module_conformance!` and in `docs/MODULE_GUIDE.md`. At least one
// injection probe is required; give one per field that reaches the rendered line,
// and one per delimiter the format uses (`#` here) as well as `\n`, `\r` and NUL.
detent_core::module_conformance!(
    TemplateModule,
    fixtures = [DEFAULT, ALIGNED, CRLF, NO_NEWLINE],
    model_strategy = model_strategy(),
    injection_probes = [
        value_probe("a\nb"),
        value_probe("a\rb"),
        value_probe("a\0b"),
        key_probe("a\nb"),
        key_probe("a b"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEFAULT, ALIGNED, CRLF, NO_NEWLINE] {
        let doc = TemplateModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(TemplateModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    TemplateModule::parse(src)
        .ok()
        .and_then(|doc| TemplateModule::to_model(&doc).ok())
        .unwrap_or_default()
}

/// Builds an expected setting.
fn expect(key: &str, value: &str) -> Setting {
    Setting {
        key: key.to_owned(),
        value: value.to_owned(),
    }
}

/// TODO(fixtures): one test per fixture, asserting the exact model. A fixture that
/// only round-trips proves losslessness but not that the parser understood it.
#[test]
fn default_fixture_parses_to_its_settings() {
    assert_eq!(
        model_of(DEFAULT),
        Model {
            settings: vec![expect("mode", "strict"), expect("backend", "systemd")]
        }
    );
}

#[test]
fn aligned_fixture_drops_alignment_and_keeps_the_unknown_line() {
    assert_eq!(
        model_of(ALIGNED),
        Model {
            settings: vec![expect("mode", "strict"), expect("backend", "systemd")]
        }
    );
}

#[test]
fn crlf_fixture_parses_without_its_terminators() {
    assert_eq!(
        model_of(CRLF),
        Model {
            settings: vec![expect("mode", "strict"), expect("backend", "systemd")]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            settings: vec![expect("mode", "strict"), expect("backend", "systemd")]
        }
    );
}

/// TODO(tests): the one property the conformance macro cannot express for you —
/// that an edit actually reaches the file, and that everything around it is left
/// alone. A module can satisfy all six invariants by refusing every edit.
#[test]
fn an_edited_value_reaches_the_rendered_file() -> Result<(), String> {
    let mut doc = TemplateModule::parse(DEFAULT).map_err(|e| e.to_string())?;
    let model = Model {
        settings: vec![expect("mode", "loose"), expect("backend", "systemd")],
    };
    let report = TemplateModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert_eq!(report.changed_lines, 1);
    assert_eq!(
        TemplateModule::render(&doc),
        "# /etc/TEMPLATE.conf\n\nmode loose\nbackend systemd\n"
    );
    Ok(())
}
