/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/audit`. */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/auth/login`. The real handler is `crate::auth::routes::login`. */
        post: operations["login_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/auth/logout`. The real handler is `crate::auth::routes::logout`. */
        post: operations["logout_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/auth/session`. The real handler is `crate::auth::routes::session`. */
        get: operations["session_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commits/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/commits/{id}/confirm`. */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commits/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/commits/{id}/rollback`. */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/modules`. */
        get: operations["list_modules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/modules/{id}`. */
        get: operations["get_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/modules/{id}/apply`. */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/modules/{id}/backups`. */
        get: operations["list_backups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}/backups/{backup_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/modules/{id}/backups/{backup_id}/restore`. */
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/modules/{id}/plan`. */
        post: operations["plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/modules/{id}/validate`. */
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/openapi.json`.
         * @description The one response body in this document that is not named by a schema: it
         *     *is* the document, and describing it would mean carrying a copy of the
         *     `OpenAPI` meta-schema.
         *
         *     The `Caller` is taken and dropped: it is not used, but taking it is what
         *     makes this route authenticated — a handler that takes no `Caller` is open
         *     by construction (see [`crate::auth::extract::Caller`]).
         */
        get: operations["serve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/services/{id}`. */
        get: operations["status"];
        put?: never;
        /** `POST /api/v1/services/{id}`. */
        post: operations["action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/cert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/system/cert`. */
        get: operations["cert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/system/profile`. */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/system/update`.
         * @description The update status the web layer answers directly: `detent-update` owns the
         *     check (release feed over the network), which the operations engine does
         *     not depend on and cannot answer for. Read-only — **installing** an update
         *     is the `write`-scoped, CSRF-checked `POST` on this same path, answered by
         *     [`apply_update`]; nothing here installs anything.
         *
         *     Interval-guarded (PLAN §2.9 steps 5a and 6): `detent update --check`
         *     (the daily cron) writes `<state_root>/update/check.json` at most once
         *     per 24 h; this handler prefers that stamp and only reaches the network
         *     when no stamp exists yet. A read-scoped caller can no longer make this
         *     host poll GitHub in a loop.
         */
        get: operations["update"];
        put?: never;
        /**
         * `POST /api/v1/system/update`.
         * @description Installs the named update: the engine bridges the release tag to the
         *     content-addressed staged file and drives the monitor's `ReplaceBinary`
         *     swap. Refused as `Unsupported` (`ops-unsupported`, 500 with a reason)
         *     when the staged file is missing or the request is unsafe; the route,
         *     authz (`write`), and audit record are the stable shape the UI builds on.
         */
        post: operations["apply_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /healthz`. The real handler is `crate::server::healthz`. */
        get: operations["healthz_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A service a change would affect. */
        AffectedService: {
            /** @description The actions the module declared, most preferred first. */
            actions: components["schemas"]["ServiceCommand"][];
            /** @description The unit name the monitor resolved for this host's init system. */
            unit: string;
        };
        /**
         * @description A [`ServiceCommand`](detent_ops::ServiceCommand), as a request body may
         *     name it.
         *
         *     [`detent_ops::ServiceCommand`] cannot derive [`utoipa::ToSchema`] without
         *     giving `detent-ops` a dependency on `utoipa`, which PLAN §2.1 forbids: the
         *     operations layer stays front-end agnostic. This is the thin mirror that
         *     lets a request body have a precise, documented schema anyway; it converts
         *     straight to the real type and carries no behaviour of its own.
         * @enum {string}
         */
        ApiServiceCommand: "restart" | "reload" | "start" | "stop";
        /** @description What [`Operation::Apply`](crate::Operation::Apply) did. */
        ApplyReport: {
            /**
             * @description Whether a backup was retained, and therefore whether commit-confirm
             *     has something to roll back to.
             */
            backed_up: boolean;
            commit?: null | components["schemas"]["PendingCommit"];
            /** @description Whether the target did not exist before. */
            created: boolean;
            /** @description The module. */
            module: string;
            /** @description Digest now on disk. */
            new_hash: components["schemas"]["Sha256Digest"];
            /** @description The target that was written. */
            path: string;
            prev_hash?: null | components["schemas"]["Sha256Digest"];
            service?: null | components["schemas"]["ServiceReport"];
        };
        /** @description The body of `POST /api/v1/modules/{id}/apply`. */
        ApplyRequest: {
            /**
             * Format: int64
             * @description Commit-confirm window, in seconds. Omitted uses the module's default;
             *     the monitor clamps whatever is armed either way.
             */
            confirm_secs?: number | null;
            /**
             * @description Digest the caller last read, as 64 lowercase hex characters. A
             *     mismatch is refused (409) rather than silently overwriting somebody
             *     else's edit.
             */
            expected_hash?: string | null;
            /** @description The candidate model. */
            model: Record<string, never>;
            service_action?: null | components["schemas"]["ApiServiceCommand"];
        };
        /** @description One argument of an [`ExternalCheck`] command line. */
        ArgTemplate: {
            /** @description A fixed argument. */
            literal: string;
        } | "temp_file";
        /** @description One line of the audit log. */
        AuditRecord: {
            /** @description Fluent id of the failure, when it failed. */
            error_id?: string | null;
            /** @description How the caller was authenticated. */
            kind: components["schemas"]["IdentityKind"];
            /** @description The module the operation was about, when it was about one. */
            module?: string | null;
            /** @description Digest of the target afterwards. */
            new_hash?: string | null;
            /** @description Which operation, without its payload. */
            op: components["schemas"]["OpKind"];
            /** @description Digest of the target before the operation, as 64 hex characters. */
            prev_hash?: string | null;
            /** @description How it ended. */
            result: components["schemas"]["AuditResult"];
            /** @description When, as RFC 3339 in UTC. */
            ts: string;
            /** @description The caller's subject. */
            who: string;
        };
        /**
         * @description How an operation ended.
         * @enum {string}
         */
        AuditResult: "ok" | "denied" | "error" | "started";
        /**
         * Format: int32
         * @description Index into the backup listing most recently produced for a module.
         */
        BackupId: number;
        /** @description One retained backup. */
        BackupInfo: {
            /**
             * Format: int64
             * @description Modification time, seconds since the Unix epoch.
             */
            created_unix_s: number;
            /** @description Digest of the backed-up contents. */
            digest: components["schemas"]["Sha256Digest"];
            /** @description Index into this listing, for [`Request::Restore`]. */
            id: components["schemas"]["BackupId"];
            /**
             * Format: int64
             * @description Size in bytes.
             */
            len: number;
            /**
             * @description File name of the backup within the module's backup directory. The
             *     directory itself is never disclosed.
             */
            name: string;
            /** @description Which target the backup came from. */
            target: components["schemas"]["TargetId"];
        };
        /**
         * @description What the serving TLS certificate looks like: its fingerprint, when it
         *     expires, and how much of its lifetime is left.
         *
         *     `not_after_unix` is `None` when the DER did not parse — reported as
         *     "unknown", never a failure: status must work even when the parse does not.
         */
        CertReport: {
            expiry_warning?: null | components["schemas"]["ExpiryWarning"];
            /** @description Uppercase colon-separated SHA-256 of the DER, as printed at startup. */
            fingerprint: string;
            /**
             * Format: int32
             * @description Whole percent of `[not_before, not_after]` elapsed at read time, when
             *     both endpoints parse. `None` means "unknown", not zero.
             */
            lifetime_used_percent?: number | null;
            /**
             * Format: int64
             * @description Validity end, whole seconds since the Unix epoch, when parseable.
             */
            not_after_unix?: number | null;
            /**
             * @description Whether two thirds of the lifetime is used (the renewal threshold).
             *     `None` when the validity window did not parse.
             */
            renewal_due?: boolean | null;
        };
        /** @description How the result of an [`ExternalCheck`] is judged. */
        CheckExpectation: "exit_zero" | {
            /**
             * @description The program's output must contain this literal substring and exit 0.
             *     Matching is a plain substring search, not a regular expression: the core
             *     deliberately carries no regex engine (PLAN §2.3), and the platform layer
             *     applies the pattern as-is. Do not write anchors or metacharacters here —
             *     `^Loaded` looks for a literal caret.
             */
            stdout_contains: string;
        };
        /** @description The result of running one of a module's upstream validators. */
        CheckReport: {
            /** @description A bounded excerpt of its output, or the reason it did not run. */
            detail: string;
            /**
             * Format: int32
             * @description Exit status, when the program was executed.
             */
            exit_code?: number | null;
            /** @description Whether the declared expectation was met. */
            passed: boolean;
            /** @description Absolute path of the validator, for display. */
            program: string;
            /**
             * @description Whether the validator actually ran. `false` means the binary is not
             *     installed or the monitor has no check runner wired up — informative,
             *     not a plan failure.
             */
            ran: boolean;
        };
        /** @description Answer to `ConfirmCommit`. */
        CommitConfirmedView: {
            /**
             * Format: int32
             * @description The commit that is now final.
             */
            commit_id: number;
        };
        /**
         * Format: int32
         * @description Identifier the caller chooses for one commit-confirm cycle.
         */
        CommitId: number;
        /**
         * @description One validation finding.
         *
         *     Built with [`Diagnostic::new`] and refined with the `with_*` methods; every field
         *     beyond severity and id is optional because not every finding maps to a field or a
         *     byte range.
         */
        Diagnostic: {
            /** @description Named arguments for the Fluent message, sorted for deterministic output. */
            args: {
                [key: string]: string;
            };
            field?: null | components["schemas"]["FieldPath"];
            /** @description The Fluent id of the message. */
            id: components["schemas"]["MessageId"];
            /** @description How much this finding matters. */
            severity: components["schemas"]["Severity"];
            span?: null | components["schemas"]["Span"];
        };
        /**
         * @description The findings from one call to `ConfigModule::validate`, in the order they were
         *     produced.
         */
        Diagnostics: components["schemas"]["Diagnostic"][];
        /**
         * @description One line of a [`Hunk`], including its own line terminator when the source
         *     line had one.
         */
        DiffLine: {
            /** @enum {string} */
            op: "context";
            /** @description Present in both texts. */
            text: string;
        } | {
            /** @enum {string} */
            op: "delete";
            /** @description Present only in the original. */
            text: string;
        } | {
            /** @enum {string} */
            op: "insert";
            /** @description Present only in the candidate. */
            text: string;
        };
        /** @description The JSON body of every API failure. */
        ErrorBody: {
            /** @description A stable machine-readable class, derived from the status. */
            code: string;
            /**
             * @description Validation findings, only present for a rejected [`Operation::Apply`]
             *     (PLAN §2.5: any `Severity::Error` diagnostic stops an apply before
             *     anything is written). Mirrors `detent_core::diag::Diagnostics`, which
             *     cannot derive `ToSchema` without giving `detent-core` a dependency on
             *     `utoipa`.
             *
             *     [`Operation::Apply`]: detent_ops::Operation::Apply
             */
            diagnostics?: Record<string, never>;
            /** @description The Fluent id a front end renders. */
            message_id: string;
        };
        /**
         * @description Certificate expiry warning level (PLAN Phase 6 failure UX): never silent
         *     about a dying certificate.
         * @enum {string}
         */
        ExpiryWarning: "half" | "quarter";
        /**
         * @description An upstream validator run against a candidate file before it is installed, e.g.
         *     `chronyd -p -f <tmp>` or `testparm -s <tmp>`.
         */
        ExternalCheck: {
            /** @description Its argument list. */
            args: components["schemas"]["ArgTemplate"][];
            /** @description The success condition. */
            expects: components["schemas"]["CheckExpectation"];
            /** @description Absolute path of the validator binary. */
            program: components["schemas"]["PathSpec"];
        };
        /**
         * @description A path to a field inside a module's model, in the style of a JSON pointer without
         *     the leading slash: `"entries/3/hostnames/0"`.
         *
         *     The UI uses it to attach a diagnostic to the control that produced it.
         */
        FieldPath: string;
        /**
         * @description What is known about the host a module is producing configuration for.
         *
         *     Populated by `detent-platform`; the core only reads it. Modules use it to pick a
         *     backend, to size defaults, and to hide options newer than the installed service.
         */
        HostProfile: {
            /** @description The host's own name, used by defaults such as the `/etc/hosts` entry for it. */
            hostname: string;
            /** @description Init system. */
            init: components["schemas"]["InitSystem"];
            /** @description Operating system family. */
            os: components["schemas"]["Os"];
            /**
             * Format: int64
             * @description Physical memory in MiB, used to size caches and worker counts.
             */
            ram_mib: number;
            /** @description Installed version per service name, e.g. `{"chronyd": "4.5"}`. */
            service_versions: {
                [key: string]: string;
            };
        };
        /**
         * @description What was detected about this host.
         *
         *     A projection rather than [`Detected`] itself: `HostFacts` and its enums are
         *     plain Rust types with no `Serialize`, and adding one there would mean
         *     editing `detent-platform`.
         */
        HostReport: {
            /** @description `ID=` from `/etc/os-release`, when the host has one. */
            distro_id?: string | null;
            /** @description `VERSION_ID=` from `/etc/os-release`. */
            distro_version_id?: string | null;
            /** @description The detected network backend. */
            network_backend: string;
            /** @description Caveats detection surfaced. */
            notes: string[];
            /** @description The profile modules see. */
            profile: components["schemas"]["HostProfile"];
            /** @description The detected resolver backend. */
            resolver_backend: string;
        };
        /**
         * @description One contiguous run of changes plus its surrounding context, addressed the
         *     way a unified diff addresses it: 1-based line numbers, and a start of `0`
         *     when the side contributes no lines at all.
         */
        Hunk: {
            /** @description The hunk body, in order. */
            lines: components["schemas"]["DiffLine"][];
            /** @description How many candidate lines this hunk covers. */
            new_lines: number;
            /** @description First candidate line covered, 1-based; `0` when `new_lines` is `0`. */
            new_start: number;
            /** @description How many original lines this hunk covers. */
            old_lines: number;
            /** @description First original line covered, 1-based; `0` when `old_lines` is `0`. */
            old_start: number;
        };
        /**
         * @description How a caller was authenticated.
         * @enum {string}
         */
        IdentityKind: "local_user" | "session" | "token";
        /**
         * @description The init system of the host being configured.
         * @enum {string}
         */
        InitSystem: "systemd" | "open_rc" | "launchd" | "none";
        /** @description The body of `POST /api/v1/auth/login`. */
        LoginRequest: {
            /** @description The password, in the clear over TLS 1.3 and nowhere else. */
            password: string;
            /**
             * @description The six-digit TOTP code, when the account has a second factor enrolled
             *     or `auth.totp_required` is set.
             */
            totp_code?: string | null;
            /** @description The account name. */
            username: string;
        };
        /**
         * @description The id of a Fluent message in `locales/<lang>/core.ftl`.
         *
         *     Always a compile-time constant, so a module cannot accidentally emit a message
         *     that has no translation entry.
         */
        MessageId: string;
        /** @description The body of `POST /api/v1/modules/{id}/validate` and `.../plan`. */
        ModelRequest: {
            /**
             * @description The candidate model, exactly as the shape `GET /modules/{id}`'s
             *     `schema` field describes.
             */
            model: Record<string, never>;
        };
        /** @description Everything a module declares about itself. */
        ModuleDescriptor: {
            /** @description Upstream validators run before installing a candidate file. */
            checks: components["schemas"]["ExternalCheck"][];
            /**
             * @description Whether a change to this module needs commit-confirm (it can lock an admin
             *     out, e.g. network configuration).
             */
            commit_confirm: boolean;
            /** @description Fluent id of the module's display name. */
            display_name_id: components["schemas"]["MessageId"];
            /**
             * @description Stable module id, e.g. `hosts`. Used in URLs, the CLI, the audit log and
             *     feature names.
             */
            id: string;
            /** @description Fluent ids of security notes shown alongside this module. */
            security_notes: components["schemas"]["MessageId"][];
            /** @description Services affected by a change. */
            services: components["schemas"]["ServiceBinding"][];
            /** @description Files and directories this module owns. */
            targets: components["schemas"]["Target"][];
            /** @description The upstream project tracked. */
            upstream: components["schemas"]["Upstream"];
        };
        /**
         * @description One module, as [`Operation::GetModule`](crate::Operation::GetModule) sees
         *     it.
         */
        ModuleView: {
            current_hash?: null | components["schemas"]["Sha256Digest"];
            /** @description The module's static metadata. */
            descriptor: components["schemas"]["ModuleDescriptor"];
            /** @description Validation findings for that model. */
            diagnostics: components["schemas"]["Diagnostics"];
            /**
             * @description The model parsed from the file on disk, or `None` when the target
             *     could not be read (e.g. it does not exist yet).
             */
            model?: Record<string, never> | null;
            /** @description The JSON Schema of its model, with `x-detent` UI hints. */
            schema: Record<string, never>;
        };
        /**
         * @description The kind of an [`Operation`], with none of its payload.
         *
         *     This is what the audit log stores: an operation's arguments include the
         *     candidate configuration, and PLAN §2.5 forbids the audit log from carrying
         *     file bodies.
         * @enum {string}
         */
        OpKind: "list_modules" | "get_module" | "validate" | "plan" | "apply" | "confirm_commit" | "rollback_commit" | "list_backups" | "restore" | "service_status" | "service_action" | "host_profile" | "audit_query" | "update_status" | "cert_status" | "cert_renew" | "update_apply";
        /**
         * @description The operating system family of the host being configured.
         * @enum {string}
         */
        Os: "linux" | "mac_os" | "other";
        /** @description The account a [`Target`] must belong to after a write. */
        Owner: "root" | {
            /** @description A named service account, e.g. `unbound`. */
            named: string;
        };
        /** @description A filesystem path owned by a module. Always a compile-time constant. */
        PathSpec: string;
        /** @description A commit-confirm window that is now running in the monitor. */
        PendingCommit: {
            /**
             * @description The id to pass to
             *     [`Operation::ConfirmCommit`](crate::Operation::ConfirmCommit).
             */
            commit_id: components["schemas"]["CommitId"];
            /** @description When the window closes, RFC 3339 UTC. */
            deadline: string;
            /**
             * Format: int32
             * @description How many targets the monitor will roll back if it expires.
             */
            rollback_targets: number;
            /**
             * Format: int32
             * @description Seconds until automatic rollback, as the monitor clamped them.
             */
            timeout_s: number;
        };
        /**
         * @description What [`Operation::Plan`](crate::Operation::Plan) found. Nothing was
         *     written.
         */
        PlanReport: {
            /** @description Services a subsequent apply could act on. */
            affected_services: components["schemas"]["AffectedService"][];
            /** @description Results of the module's upstream validators, run against the candidate. */
            checks: components["schemas"]["CheckReport"][];
            /** @description Digest of the file as it is now, to pass back as `expected_hash`. */
            current_hash: components["schemas"]["Sha256Digest"];
            /** @description Validation findings for the candidate model. */
            diagnostics: components["schemas"]["Diagnostics"];
            /** @description The change, as unified-diff hunks. */
            diff: components["schemas"]["Hunk"][];
            /** @description The module. */
            module: string;
            /** @description The target this plan is about. */
            path: string;
            /** @description The candidate file, rendered in full. */
            rendered: string;
            /**
             * @description `diff` as unified-diff text, so a front end and the CLI show the same
             *     bytes without each re-implementing the rendering.
             */
            unified_diff: string;
            /** @description Whether applying would change anything at all. */
            would_change: boolean;
        };
        /** @description Answer to `Restore`. */
        RestoredView: {
            /** @description Digest now on disk, 64 lowercase hex characters. */
            new_hash: string;
            /**
             * Format: int32
             * @description The target that was put back, as the monitor's index for it.
             */
            target: number;
        };
        /** @description Answer to `RollbackCommit`. */
        RolledBackView: {
            /**
             * Format: int32
             * @description The commit that was rolled back.
             */
            commit_id: number;
            /**
             * Format: int32
             * @description How many targets were actually restored.
             */
            restored: number;
        };
        /**
         * @description What may be done to a service after a config change.
         * @enum {string}
         */
        ServiceAction: "restart" | "reload" | "start" | "stop";
        /** @description The body of `POST /api/v1/services/{id}`. */
        ServiceActionRequest: {
            /** @description What to do. */
            action: components["schemas"]["ApiServiceCommand"];
        };
        /** @description A service a module's files configure. */
        ServiceBinding: {
            /** @description Actions this module may request, most preferred first. */
            actions: components["schemas"]["ServiceAction"][];
            /** @description Names of the service per init system. */
            units: components["schemas"]["UnitNames"];
        };
        /**
         * @description What a caller may ask be done to a service.
         *
         *     A closed mirror of [`CoreServiceAction`] that, unlike the core type, is
         *     `Deserialize` (so it can arrive over an API) and, unlike the wire type,
         *     has no `Status` variant — status is [`Operation::ServiceStatus`], which
         *     mutates nothing and must not be confusable with an action that does.
         * @enum {string}
         */
        ServiceCommand: "restart" | "reload" | "start" | "stop";
        /** @description What happened to a service. */
        ServiceReport: {
            /** @description The action that was requested. */
            action: components["schemas"]["ServiceCommand"];
            /** @description Whether the unit is running afterwards. */
            active: boolean;
            /** @description A short human-readable detail string. */
            detail: string;
            /** @description The unit the monitor acted on. */
            unit: string;
        };
        /** @description The result of a [`ServiceManager::status`] call. */
        ServiceStatus: {
            /**
             * @description Whether the unit starts automatically at boot, when the backend can
             *     determine it.
             */
            enabled?: boolean | null;
            since?: null | components["schemas"]["SystemTimeView"];
            /** @description Current run state. */
            state: components["schemas"]["State"];
            /**
             * @description The unit name actually resolved and queried, i.e. the alternative
             *     from [`UnitNames`] that exists on this host.
             */
            unit: string;
        };
        /**
         * @description What `GET /api/v1/auth/session` answers.
         *
         *     The session **id** is deliberately absent: the browser already holds it in
         *     a `HttpOnly` cookie, and a copy of it in a readable response body would
         *     undo that.
         */
        SessionView: {
            /** @description The token to echo in `X-Detent-CSRF`. */
            csrf_token: string;
            /**
             * Format: int64
             * @description Seconds until the session expires, idle and absolute limits combined.
             */
            expires_in_secs: number;
            /** @description Scope names, `["read"]` or `["read", "write"]`. */
            scopes: string[];
            /** @description The user this session belongs to. */
            subject: string;
            /** @description Whether a second factor was presented. */
            totp_satisfied: boolean;
        };
        /**
         * @description How much a diagnostic matters.
         * @enum {string}
         */
        Severity: "error" | "warning" | "recommendation";
        /** @description A SHA-256 digest, as 64 lowercase hex characters. */
        Sha256Digest: string;
        /**
         * @description A byte range within the text a [`Document`] was parsed from.
         *
         *     `start` is inclusive, `end` is exclusive. Both are byte offsets, not character
         *     offsets, and always fall on UTF-8 boundaries.
         */
        Span: {
            /** @description Exclusive end byte offset. */
            end: number;
            /** @description Inclusive start byte offset. */
            start: number;
        };
        /**
         * @description The run state of a service, as reported by [`ServiceManager::status`].
         * @enum {string}
         */
        State: "active" | "inactive" | "failed" | "activating" | "deactivating" | "unknown";
        /**
         * @description How `serde` renders a [`SystemTime`]: two integers, not an RFC 3339
         *     string.
         *
         *     It exists only so the `openapi` feature has something accurate to point
         *     [`ServiceStatus::since`] at — `utoipa` has no schema for [`SystemTime`],
         *     and describing it as a string would misdescribe the bytes clients receive.
         *     Nothing constructs one.
         */
        SystemTimeView: {
            /**
             * Format: int32
             * @description Nanoseconds within that second.
             */
            nanos_since_epoch: number;
            /**
             * Format: int64
             * @description Whole seconds since the Unix epoch.
             */
            secs_since_epoch: number;
        };
        /** @description One file or directory a module manages. */
        Target: {
            /** @description File, drop-in directory, or directory. */
            kind: components["schemas"]["TargetKind"];
            /**
             * Format: int32
             * @description The mode the target must end up with, e.g. `0o644`.
             */
            mode: number;
            /** @description The owner the target must end up with. */
            owner: components["schemas"]["Owner"];
            /** @description Where it lives. */
            path: components["schemas"]["PathSpec"];
        };
        /**
         * Format: int32
         * @description Index into the monitor's target table.
         */
        TargetId: number;
        /**
         * @description What kind of filesystem object a [`Target`] is.
         * @enum {string}
         */
        TargetKind: "file" | "drop_in_dir" | "directory";
        /**
         * @description Per-init-system names for one service, most preferred first.
         *
         *     Distributions disagree (`chronyd.service` on Fedora, `chrony.service` on Debian),
         *     so each backend gets a list of alternatives rather than a single name.
         */
        UnitNames: {
            /** @description BSD `rc.d` script names. Kept for portability; BSD is a deferred tier. */
            bsdrc: string[];
            /** @description `OpenRC` service names. */
            openrc: string[];
            /** @description systemd unit names. */
            systemd: string[];
        };
        /** @description Answer to `UpdateApply`. */
        UpdateAppliedView: {
            /** @description The version that was installed. */
            version: string;
        };
        /** @description The body of `POST /api/v1/system/update`. */
        UpdateApplyRequest: {
            /** @description The update version to install, e.g. `v1.2.3`. */
            version: string;
        };
        /**
         * @description The answer body of `GET /api/v1/system/update`.
         *
         *     A mirror of [`CheckReport`], not a re-export: `detent-update` has no
         *     `utoipa` dependency by design (PLAN §2.1 keeps the update crate
         *     front-end agnostic), so this is the thin mirror that documents the schema,
         *     the same move [`super::ApiServiceCommand`] makes for `ServiceCommand`.
         *     Field-for-field identical and converted, never copied by hand.
         */
        UpdateReport: {
            /** @description The running version. */
            current: string;
            /** @description When the release was published, RFC 3339. */
            published?: string | null;
            /** @description Whether it bypassed the age gate via `detent-security: true`. */
            security: boolean;
            /** @description The qualifying tag, when one exists. */
            tag?: string | null;
            /** @description Whether a qualifying release exists. */
            update_available: boolean;
        };
        /** @description The upstream project whose configuration format a module tracks. */
        Upstream: {
            /** @description Documentation URLs shown in the UI. */
            docs: string[];
            /** @description Upstream project name, e.g. `chrony`. */
            project: string;
            /** @description A release feed URL the upstream-watch workflow polls, when one exists. */
            release_feed?: string | null;
            /** @description Canonical source repository URL. */
            repo_url: string;
            /** @description The upstream release this module's option set was derived from. */
            tracked_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit: {
        parameters: {
            query?: {
                /** @description Only records about this module. At most [`MAX_FILTER_LEN`] bytes. */
                module?: string;
                /** @description Only records from this subject. At most [`MAX_FILTER_LEN`] bytes. */
                who?: string;
                /**
                 * @description At most this many records, newest first, capped at
                 *     [`MAX_AUDIT_LIMIT`].
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching audit records, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
        };
    };
    login_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; the session cookie is set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description The credentials were refused */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended; the cookie is cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session to end */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    session_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session's CSRF token, scopes and expiry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description No session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Commit id `Apply` returned */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The commit is now final */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitConfirmedView"];
                };
            };
            /** @description No such commit is pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Commit id `Apply` returned */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every write since the commit was armed is undone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolledBackView"];
                };
            };
            /** @description No such commit is pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_modules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every module compiled into this build */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleDescriptor"][];
                };
            };
        };
    };
    get_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The module's descriptor, schema, current model and diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleView"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description What was written, and any service action or commit-confirm window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyReport"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The target changed since `expected_hash` was read */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The candidate has at least one error diagnostic */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_backups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The module's retained backups, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupInfo"][];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
                /** @description Index into `GET .../backups` */
                backup_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The backup was put back */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoredView"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Diff and validator results; nothing is written */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanReport"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Validation findings for the candidate model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostics"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    serve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service's run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The module declares no service */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceActionRequest"];
            };
        };
        responses: {
            /** @description What happened to the service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceReport"];
                };
            };
            /** @description No such module */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The module declares no service */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serving certificate status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertReport"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What was detected about this host */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostReport"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The update status under the configured policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateReport"];
                };
            };
            /** @description The release feed could not be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    apply_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplyRequest"];
            };
        };
        responses: {
            /** @description The update was installed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateAppliedView"];
                };
            };
            /** @description No staged binary to install */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    healthz_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is serving */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
