//! Conformance suite for the `resolver` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.

use detent_core::module::ConfigModule;
use detent_module_resolver::{
    DnsServer, Model, ResolvEntry, ResolvedDnsOverTls, ResolvedDnsSec, ResolvedEntry,
    ResolverModule, UnboundEntry,
};
use proptest::prelude::{Just, Strategy, any, prop_oneof};
use std::net::{IpAddr, Ipv4Addr};

/// Debian's static `/etc/resolv.conf` (glibc 2.42-era, no local resolver backend).
const RESOLV: &str = include_str!("../../../../fixtures/resolver/glibc-2.42/resolv-default.conf");
/// systemd 257's shipped `/etc/systemd/resolved.conf`, with hand-added servers.
const RESOLVED: &str =
    include_str!("../../../../fixtures/resolver/resolved-257/resolved-default.conf");
/// `NLnetLabs` unbound 1.24's stock `unbound.conf` clauses plus a `DoT` forward zone.
const UNBOUND: &str =
    include_str!("../../../../fixtures/resolver/unbound-1.24/unbound-default.conf");
/// Every line terminated with `\r\n`, spanning all three flavors.
const CRLF: &str = include_str!("../../../../fixtures/resolver/edge/crlf-resolv.conf");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str =
    include_str!("../../../../fixtures/resolver/edge/no-trailing-newline.conf");
/// Tab-aligned tokens and unbound's tab-indented attributes.
const TABS: &str = include_str!("../../../../fixtures/resolver/edge/tabs-and-spacing.conf");
/// Directives this module never rewrites: `sortlist`, `lookup`.
const UNKNOWN: &str = include_str!("../../../../fixtures/resolver/edge/unknown-directives.conf");

/// Valid models: 0–6 entries per flavor, addresses RFC 1123-shaped, domains
/// RFC 1035-shaped with optional `~` marker and trailing dot, option tokens and
/// unbound keys from the modeled sets. Everything a generated model contains
/// must survive `render_*`'s round-trip check, so `check_edit_fidelity` and
/// `check_idempotent` exercise `apply` rather than its rejection path.
fn ip_strategy() -> impl Strategy<Value = IpAddr> {
    prop_oneof![
        any::<[u8; 4]>().prop_map(IpAddr::from),
        any::<[u8; 16]>().prop_map(IpAddr::from),
    ]
}

fn domain_strategy() -> impl Strategy<Value = String> {
    let label = "[a-z][a-z0-9-]{0,7}";
    prop_oneof![
        Just(".".to_owned()),
        (("~", label), proptest::option::of("."),).prop_map(
            |((tilde, label), dot): ((String, String), Option<String>)| {
                format!("{tilde}{label}{}", dot.as_deref().unwrap_or(""))
            }
        ),
    ]
}

fn resolv_strategy() -> impl Strategy<Value = ResolvEntry> {
    prop_oneof![
        ip_strategy().prop_map(|ip| ResolvEntry::Nameserver { ip }),
        proptest::collection::vec(domain_strategy(), 1..=3)
            .prop_map(|domains| ResolvEntry::Search { domains }),
        domain_strategy().prop_map(|domain| ResolvEntry::Domain { domain }),
        proptest::collection::vec(
            prop_oneof![
                Just("edns0".to_owned()),
                Just("trust-ad".to_owned()),
                Just("ndots:2".to_owned()),
                Just("timeout:5".to_owned()),
                Just("attempts:2".to_owned()),
            ],
            1..=3,
        )
        .prop_map(|options| ResolvEntry::Options { options }),
    ]
}

fn server_strategy() -> impl Strategy<Value = DnsServer> {
    (ip_strategy(), proptest::option::of(domain_strategy()))
        .prop_map(|(ip, name)| DnsServer { ip, name })
}

fn resolved_strategy() -> impl Strategy<Value = ResolvedEntry> {
    prop_oneof![
        Just(ResolvedEntry::Resolve),
        proptest::collection::vec(server_strategy(), 0..=3)
            .prop_map(|servers| ResolvedEntry::Dns { servers }),
        proptest::collection::vec(server_strategy(), 0..=3)
            .prop_map(|servers| ResolvedEntry::FallbackDns { servers }),
        proptest::collection::vec(domain_strategy(), 1..=3)
            .prop_map(|domains| ResolvedEntry::Domains { domains }),
        prop_oneof![
            Just(ResolvedDnsSec::Yes),
            Just(ResolvedDnsSec::No),
            Just(ResolvedDnsSec::AllowDowngrade),
        ]
        .prop_map(|mode| ResolvedEntry::DnsSec { mode }),
        prop_oneof![
            Just(ResolvedDnsOverTls::Yes),
            Just(ResolvedDnsOverTls::No),
            Just(ResolvedDnsOverTls::Opportunistic),
        ]
        .prop_map(|mode| ResolvedEntry::DnsOverTls { mode }),
    ]
}

fn unbound_strategy() -> impl Strategy<Value = UnboundEntry> {
    prop_oneof![
        Just(UnboundEntry::Server),
        Just(UnboundEntry::ForwardZone),
        (
            prop_oneof![
                Just("qname-minimisation"),
                Just("qname-minimisation-strict"),
                Just("aggressive-nsec"),
                Just("harden-glue"),
                Just("harden-dnssec-stripped"),
                Just("harden-below-nxdomain"),
                Just("harden-referral-path"),
                Just("hide-identity"),
                Just("hide-version"),
            ],
            any::<bool>(),
        )
            .prop_map(|(key, enabled)| UnboundEntry::Hardening {
                key: key.to_owned(),
                enabled,
            }),
        domain_strategy().prop_map(|name| UnboundEntry::ForwardName { name }),
        (
            ip_strategy(),
            proptest::option::of(any::<u16>()),
            proptest::option::of(domain_strategy()),
        )
            .prop_map(|(ip, port, auth)| UnboundEntry::ForwardAddr {
                addr: match (port, auth) {
                    (Some(port), Some(name)) => format!("{ip}@{port}#{name}"),
                    (Some(port), None) => format!("{ip}@{port}"),
                    (None, Some(name)) => format!("{ip}#{name}"),
                    (None, None) => ip.to_string(),
                },
            }),
        any::<bool>().prop_map(|enabled| UnboundEntry::ForwardTls { enabled }),
    ]
}

fn model_strategy() -> impl Strategy<Value = Model> {
    (
        proptest::collection::vec(resolv_strategy(), 0..=6),
        proptest::collection::vec(resolved_strategy(), 0..=6),
        proptest::collection::vec(unbound_strategy(), 0..=6),
    )
        .prop_map(|(resolv, resolved, unbound)| Model {
            resolv,
            resolved,
            unbound,
        })
}

/// A model whose search domain carries `value`, for invariant 5.
fn domain_probe(value: &str) -> Model {
    Model {
        resolv: vec![ResolvEntry::Search {
            domains: vec![value.to_owned()],
        }],
        ..Model::default()
    }
}

/// A model whose option token carries `value`, for invariant 5.
fn option_probe(value: &str) -> Model {
    Model {
        resolv: vec![ResolvEntry::Options {
            options: vec![value.to_owned()],
        }],
        ..Model::default()
    }
}

/// A model whose DNS server auth name carries `value`, for invariant 5.
fn server_name_probe(value: &str) -> Model {
    Model {
        resolved: vec![ResolvedEntry::Dns {
            servers: vec![DnsServer {
                ip: "192.0.2.1"
                    .parse()
                    .unwrap_or(IpAddr::V4(Ipv4Addr::UNSPECIFIED)),
                name: Some(value.to_owned()),
            }],
        }],
        ..Model::default()
    }
}

/// A model whose unbound forward-zone name carries `value`, for invariant 5.
fn forward_name_probe(value: &str) -> Model {
    Model {
        unbound: vec![UnboundEntry::ForwardName {
            name: value.to_owned(),
        }],
        ..Model::default()
    }
}

detent_core::module_conformance!(
    ResolverModule,
    fixtures = [RESOLV, RESOLVED, UNBOUND, CRLF, NO_NEWLINE, TABS, UNKNOWN],
    model_strategy = model_strategy(),
    injection_probes = [
        domain_probe("a\nb"),
        domain_probe("a\rb"),
        domain_probe("a\0b"),
        option_probe("a\nb"),
        option_probe("a\0b"),
        server_name_probe("a\nb"),
        server_name_probe("a\0b"),
        forward_name_probe("a\nb"),
        forward_name_probe("a\0b"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [RESOLV, RESOLVED, UNBOUND, CRLF, NO_NEWLINE, TABS, UNKNOWN] {
        let doc = ResolverModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(ResolverModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    ResolverModule::parse(src)
        .ok()
        .and_then(|doc| ResolverModule::to_model(&doc).ok())
        .unwrap_or_default()
}

fn ns_at(ip: &str) -> ResolvEntry {
    ResolvEntry::Nameserver {
        ip: ip.parse().unwrap_or(IpAddr::V4(Ipv4Addr::UNSPECIFIED)),
    }
}

fn server(ip: &str, name: Option<&str>) -> DnsServer {
    DnsServer {
        ip: ip.parse().unwrap_or(IpAddr::V4(Ipv4Addr::UNSPECIFIED)),
        name: name.map(str::to_owned),
    }
}

#[test]
fn resolv_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(RESOLV),
        Model {
            resolv: vec![
                ns_at("192.168.1.1"),
                ResolvEntry::Search {
                    domains: vec!["lan".to_owned()]
                },
                ResolvEntry::Options {
                    options: vec!["ndots:2".to_owned(), "edns0".to_owned()]
                },
            ],
            ..Model::default()
        }
    );
}

#[test]
fn resolved_fixture_parses_to_its_settings() {
    assert_eq!(
        model_of(RESOLVED),
        Model {
            resolved: vec![
                ResolvedEntry::Resolve,
                ResolvedEntry::Dns {
                    servers: vec![
                        server("9.9.9.9", Some("dns.quad9.net")),
                        server("149.112.112.112", Some("dns.quad9.net")),
                    ]
                },
                ResolvedEntry::DnsSec {
                    mode: ResolvedDnsSec::AllowDowngrade
                },
                ResolvedEntry::DnsOverTls {
                    mode: ResolvedDnsOverTls::Opportunistic
                },
            ],
            ..Model::default()
        }
    );
}

#[test]
fn unbound_fixture_parses_to_its_items() {
    assert_eq!(
        model_of(UNBOUND),
        Model {
            unbound: vec![
                UnboundEntry::Server,
                UnboundEntry::Hardening {
                    key: "qname-minimisation".to_owned(),
                    enabled: true,
                },
                UnboundEntry::Hardening {
                    key: "harden-dnssec-stripped".to_owned(),
                    enabled: true,
                },
                UnboundEntry::Hardening {
                    key: "harden-below-nxdomain".to_owned(),
                    enabled: true,
                },
                UnboundEntry::Hardening {
                    key: "aggressive-nsec".to_owned(),
                    enabled: true,
                },
                UnboundEntry::Hardening {
                    key: "hide-identity".to_owned(),
                    enabled: true,
                },
                UnboundEntry::Hardening {
                    key: "hide-version".to_owned(),
                    enabled: true,
                },
                UnboundEntry::ForwardZone,
                UnboundEntry::ForwardName {
                    name: ".".to_owned()
                },
                UnboundEntry::ForwardTls { enabled: true },
                UnboundEntry::ForwardAddr {
                    addr: "9.9.9.9@853#dns.quad9.net".to_owned()
                },
                UnboundEntry::ForwardAddr {
                    addr: "149.112.112.112@853#dns.quad9.net".to_owned()
                },
            ],
            ..Model::default()
        }
    );
}

#[test]
fn crlf_fixture_keeps_its_terminators_and_all_three_flavors() {
    assert_eq!(
        model_of(CRLF),
        Model {
            resolv: vec![
                ns_at("127.0.0.1"),
                ResolvEntry::Search {
                    domains: vec!["lan".to_owned()]
                },
                ns_at("192.168.1.1"),
                ResolvEntry::Options {
                    options: vec!["ndots:2".to_owned(), "timeout:5".to_owned()]
                },
                ns_at("192.0.2.53"),
            ],
            resolved: vec![
                ResolvedEntry::Resolve,
                ResolvedEntry::DnsSec {
                    mode: ResolvedDnsSec::No
                },
                ResolvedEntry::DnsOverTls {
                    mode: ResolvedDnsOverTls::No
                },
            ],
            ..Model::default()
        }
    );
}

#[test]
fn tabs_and_indentation_survive_a_noop_edit() {
    // The fixture must round-trip byte for byte (checked by the macro's
    // invariant 1) and parse to these entries.
    assert_eq!(
        model_of(TABS),
        Model {
            resolv: vec![
                ns_at("192.0.2.1"),
                ResolvEntry::Search {
                    domains: vec!["lan".to_owned()]
                },
                ResolvEntry::Options {
                    options: vec!["ndots:2".to_owned(), "edns0".to_owned()]
                },
            ],
            unbound: vec![
                UnboundEntry::ForwardTls { enabled: true },
                UnboundEntry::ForwardAddr {
                    addr: "192.0.2.53@853".to_owned()
                },
                UnboundEntry::Server,
                UnboundEntry::Hardening {
                    key: "hide-identity".to_owned(),
                    enabled: true,
                },
            ],
            ..Model::default()
        }
    );
}

#[test]
fn unknown_directives_stay_out_of_the_model() {
    assert_eq!(
        model_of(UNKNOWN),
        Model {
            resolv: vec![
                ns_at("192.0.2.1"),
                ResolvEntry::Search {
                    domains: vec!["lan".to_owned()]
                },
                ns_at("192.0.2.53")
            ],
            ..Model::default()
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            resolv: vec![
                ns_at("192.0.2.1"),
                ResolvEntry::Search {
                    domains: vec!["lan".to_owned()]
                },
                ns_at("192.0.2.53"),
            ],
            ..Model::default()
        }
    );
}
