//! Conformance suite for the `mounts` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.

use detent_core::module::ConfigModule;
use detent_module_mounts::{Entry, Model, MountsModule};
use proptest::prelude::{Just, Strategy, prop_oneof};

/// A stock fstab: comments, blanks, UUID specs, hand-aligned columns.
const DEFAULT: &str = include_str!("../../../../fixtures/mounts/util-linux-2.42.3/fstab-default");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/mounts/edge/crlf.fstab");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/mounts/edge/no-trailing-newline.fstab");
/// Hand-aligned columns and mixed tabs.
const TABS: &str = include_str!("../../../../fixtures/mounts/edge/tabs-and-spacing.fstab");
/// A valid entry with x-options, plus lines that cannot split into six fields.
const UNKNOWN: &str = include_str!("../../../../fixtures/mounts/edge/unknown-directives.fstab");

/// Builds an expected entry.
fn entry(
    spec: &str,
    mountpoint: &str,
    fstype: &str,
    options: &[&str],
    dump: u8,
    pass: u8,
) -> Entry {
    Entry {
        spec: spec.to_owned(),
        mountpoint: mountpoint.to_owned(),
        fstype: fstype.to_owned(),
        options: options.iter().map(|option| (*option).to_owned()).collect(),
        dump,
        pass,
    }
}

/// Valid models: 0–20 entries with whitespace-free fields and non-empty option
/// words, so `apply` never refuses one and invariants 3 and 4 stay meaningful.
fn model_strategy() -> impl Strategy<Value = Model> {
    let mountpoint = prop_oneof![
        Just("/".to_owned()),
        "[a-z][a-z0-9./_-]{0,13}".prop_map(|rest| format!("/{rest}")),
    ];
    let entry_strategy = (
        "[A-Za-z0-9=./_-]{1,15}",
        mountpoint,
        "[a-z][a-z0-9.-]{0,7}",
        proptest::collection::vec("[a-z][a-z0-9._=-]{0,9}", 1..=4),
        0u8..=1,
        0u8..=2,
    )
        .prop_map(|(spec, mountpoint, fstype, options, dump, pass)| Entry {
            spec,
            mountpoint,
            fstype,
            options,
            dump,
            pass,
        });
    proptest::collection::vec(entry_strategy, 0..=20).prop_map(|entries| Model { entries })
}

/// A model whose spec carries `value`, for invariant 5.
fn spec_probe(value: &str) -> Model {
    Model {
        entries: vec![entry(value, "/", "ext4", &["defaults"], 0, 1)],
    }
}

/// A model whose mountpoint carries `value`, for invariant 5.
fn mountpoint_probe(value: &str) -> Model {
    Model {
        entries: vec![entry("UUID=probe", value, "ext4", &["defaults"], 0, 1)],
    }
}

/// A model whose fstype carries `value`, for invariant 5.
fn fstype_probe(value: &str) -> Model {
    Model {
        entries: vec![entry("UUID=probe", "/", value, &["defaults"], 0, 1)],
    }
}

/// A model whose options carry `value` as one option word.
fn options_probe(value: &str) -> Model {
    Model {
        entries: vec![entry(
            "UUID=probe",
            "/srv",
            "ext4",
            &["defaults", value],
            0,
            2,
        )],
    }
}

detent_core::module_conformance!(
    MountsModule,
    fixtures = [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN],
    model_strategy = model_strategy(),
    injection_probes = [
        // spec: line breaks, NUL, a field-splitting space, and the comment prefix.
        spec_probe("a\nb"),
        spec_probe("a\rb"),
        spec_probe("a\0b"),
        spec_probe("a b"),
        spec_probe("#x"),
        mountpoint_probe("a\nb"),
        mountpoint_probe("a\rb"),
        mountpoint_probe("a b"),
        fstype_probe("a\nb"),
        fstype_probe("a b"),
        options_probe("a\nb"),
        options_probe("a\0b"),
        options_probe("a b"),
        options_probe("a,b"),
        options_probe("a,"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN] {
        let doc = MountsModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(MountsModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    MountsModule::parse(src)
        .ok()
        .and_then(|doc| MountsModule::to_model(&doc).ok())
        .unwrap_or_default()
}

#[test]
fn default_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(DEFAULT),
        Model {
            entries: vec![
                entry(
                    "UUID=e2a4b8c6-1f2d-4a3b-9c8d-0e1f2a3b4c5d",
                    "/",
                    "ext4",
                    &["defaults"],
                    0,
                    1
                ),
                entry(
                    "UUID=7d3c2a1b-0e9f-4d8c-8b7a-6f5e4d3c2b1a",
                    "/home",
                    "ext4",
                    &["defaults", "nodev", "nosuid"],
                    0,
                    2,
                ),
                entry(
                    "UUID=aa11bb22-cc33-dd44-ee55-ff66aa77bb88",
                    "none",
                    "swap",
                    &["sw"],
                    0,
                    0,
                ),
            ]
        }
    );
}

#[test]
fn crlf_fixture_keeps_its_terminators_and_entries() {
    assert_eq!(
        model_of(CRLF),
        Model {
            entries: vec![
                entry(
                    "UUID=e2a4b8c6-1f2d-4a3b-9c8d-0e1f2a3b4c5d",
                    "/",
                    "ext4",
                    &["defaults"],
                    0,
                    1,
                ),
                entry(
                    "UUID=aa11bb22-cc33-dd44-ee55-ff66aa77bb88",
                    "none",
                    "swap",
                    &["sw"],
                    0,
                    0,
                ),
                entry(
                    "UUID=7d3c2a1b-0e9f-4d8c-8b7a-6f5e4d3c2b1a",
                    "/home",
                    "ext4",
                    &["defaults"],
                    0,
                    2,
                ),
            ]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            entries: vec![
                entry(
                    "UUID=e2a4b8c6-1f2d-4a3b-9c8d-0e1f2a3b4c5d",
                    "/",
                    "ext4",
                    &["defaults"],
                    0,
                    1,
                ),
                entry(
                    "UUID=7d3c2a1b-0e9f-4d8c-8b7a-6f5e4d3c2b1a",
                    "/home",
                    "ext4",
                    &["defaults", "nodev"],
                    0,
                    2,
                ),
            ]
        }
    );
}

#[test]
fn tabs_and_spacing_fixture_drops_alignment_but_keeps_entries() {
    assert_eq!(
        model_of(TABS),
        Model {
            entries: vec![
                entry(
                    "UUID=e2a4b8c6-1f2d-4a3b-9c8d-0e1f2a3b4c5d",
                    "/",
                    "ext4",
                    &["defaults"],
                    0,
                    1,
                ),
                entry(
                    "UUID=7d3c2a1b-0e9f-4d8c-8b7a-6f5e4d3c2b1a",
                    "/home",
                    "ext4",
                    &["defaults"],
                    0,
                    2,
                ),
                entry(
                    "tmpfs",
                    "/dev/shm",
                    "tmpfs",
                    &["defaults", "nosuid", "nodev"],
                    0,
                    0,
                ),
            ]
        }
    );
}

#[test]
fn garbage_lines_stay_unknown_and_x_options_parse_as_options() {
    assert_eq!(
        model_of(UNKNOWN),
        Model {
            entries: vec![entry(
                "UUID=1c2d3e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f",
                "/data/nas",
                "cifs",
                &[
                    "credentials=/etc/nas.cred",
                    "x-systemd.automount",
                    "x-systemd.idle-timeout=60",
                ],
                0,
                0,
            ),]
        }
    );
}
