//! Conformance suite for the `nfs` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.

use detent_core::module::ConfigModule;
use detent_module_nfs::{Client, Export, Model, NfsModule};
use proptest::prelude::Strategy;

/// The stock `/etc/exports` sample.
const DEFAULT: &str =
    include_str!("../../../../fixtures/nfs/nfs-utils-2.9.2/exports-default.exports");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/nfs/edge/crlf.exports");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/nfs/edge/no-trailing-newline.exports");
/// Hand-aligned columns and an empty option list.
const TABS: &str = include_str!("../../../../fixtures/nfs/edge/tabs-and-spacing.exports");
/// Kerberos-style options and lines this module does not model: unbalanced
/// parens, a quoted path with spaces, the deprecated `@(netgroup)(...)` spelling.
const UNKNOWN: &str = include_str!("../../../../fixtures/nfs/edge/unknown-directives.exports");

/// Valid models: 0–10 exports, each an absolute path of `/`-separated segments
/// and 0–3 clients, each 0–3 bare option tokens — no whitespace, no parens, so
/// every generated model survives `render_line` and the invariants 3/4 checks
/// are never vacuous.
fn model_strategy() -> impl Strategy<Value = Model> {
    let path = "[a-z]{1,8}(/[a-z0-9_-]{1,8}){0,2}".prop_map(|p| format!("/{p}"));
    let host = "[a-z0-9*?@][a-z0-9*?@.-]{0,8}";
    let option = "[a-z0-9_]{1,10}";
    let client = (host, proptest::collection::vec(option, 0..=3))
        .prop_map(|(host, options)| Client { host, options });
    let export = (path, proptest::collection::vec(client, 0..=3))
        .prop_map(|(path, clients)| Export { path, clients });
    proptest::collection::vec(export, 0..=10).prop_map(|entries| Model { entries })
}

/// A model whose client option carries `value`, for invariant 5.
fn option_probe(value: &str) -> Model {
    Model {
        entries: vec![Export {
            path: "/srv/probe".to_owned(),
            clients: vec![Client {
                host: "probe.lan".to_owned(),
                options: vec![value.to_owned()],
            }],
        }],
    }
}

/// A model whose client host carries `value`, for invariant 5.
fn host_probe(value: &str) -> Model {
    Model {
        entries: vec![Export {
            path: "/srv/probe".to_owned(),
            clients: vec![Client {
                host: value.to_owned(),
                options: vec!["rw".to_owned()],
            }],
        }],
    }
}

/// A model whose export path carries `value`, for invariant 5.
fn path_probe(value: &str) -> Model {
    Model {
        entries: vec![Export {
            path: value.to_owned(),
            clients: vec![Client {
                host: "probe.lan".to_owned(),
                options: vec!["rw".to_owned()],
            }],
        }],
    }
}

detent_core::module_conformance!(
    NfsModule,
    fixtures = [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN],
    model_strategy = model_strategy(),
    injection_probes = [
        option_probe("a\nb"),
        option_probe("a\0b"),
        host_probe("a\nb"),
        host_probe("a\rb"),
        path_probe("a\nb"),
        // A host with a space and a path with a space do not carry a line break,
        // but neither survives the render/parse round trip, so `apply` must
        // refuse them too.
        host_probe("a b"),
        path_probe("a b"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN] {
        let doc = NfsModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(NfsModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    NfsModule::parse(src)
        .ok()
        .and_then(|doc| NfsModule::to_model(&doc).ok())
        .unwrap_or_default()
}

/// Builds an expected export.
fn expect_export(path: &str, clients: &[(&str, &[&str])]) -> Export {
    Export {
        path: path.to_owned(),
        clients: clients
            .iter()
            .map(|(host, options)| Client {
                host: (*host).to_owned(),
                options: options.iter().map(|o| (*o).to_owned()).collect(),
            })
            .collect(),
    }
}

#[test]
fn default_fixture_parses_to_its_exports() {
    assert_eq!(
        model_of(DEFAULT),
        Model {
            entries: vec![
                expect_export(
                    "/srv/nfs4",
                    &[("192.168.1.0/24", &["rw", "sync", "no_subtree_check"])]
                ),
                expect_export(
                    "/srv/nfs4/home",
                    &[("192.168.1.0/24", &["rw", "sync", "no_subtree_check"])]
                ),
            ]
        }
    );
}

#[test]
fn crlf_fixture_keeps_its_terminators_and_comment() {
    assert_eq!(
        model_of(CRLF),
        Model {
            entries: vec![
                expect_export(
                    "/srv/nfs4",
                    &[("192.168.1.0/24", &["rw", "sync", "no_subtree_check"])]
                ),
                expect_export("/srv/nfs4/home", &[("192.168.1.0/24", &["rw", "sync"])]),
            ]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            entries: vec![
                expect_export(
                    "/srv/nfs4",
                    &[("192.168.1.0/24", &["rw", "sync", "no_subtree_check"])]
                ),
                expect_export("/srv/nfs4/home", &[("192.168.1.0/24", &["rw", "sync"])]),
            ]
        }
    );
}

#[test]
fn tabs_fixture_drops_nothing_and_keeps_empty_options() {
    assert_eq!(
        model_of(TABS),
        Model {
            entries: vec![
                expect_export("/srv/data", &[("file-a.lan", &["rw", "sync"])]),
                expect_export(
                    "/srv/db",
                    &[
                        ("db1.lan", &["rw", "sync"]),
                        ("db2.lan", &["ro", "no_subtree_check"])
                    ]
                ),
                expect_export("/srv/tmp", &[("tmp.lan", &[])]),
            ]
        }
    );
}

#[test]
fn unknown_fixture_keeps_kerberos_and_drops_the_rest() {
    assert_eq!(
        model_of(UNKNOWN),
        Model {
            entries: vec![
                expect_export(
                    "/srv/krb5",
                    &[("@trusted", &["sec=krb5p:krb5i", "rw", "sync"])]
                ),
                expect_export("/srv/gss", &[("gssbox.lan", &["sec=krb5p", "rw", "sync"])]),
            ]
        }
    );
}

/// The one property the conformance macro cannot express for you — that an edit
/// actually reaches the file, and that everything around it is left alone. A
/// module can satisfy all six invariants by refusing every edit.
#[test]
fn an_edited_export_reaches_the_rendered_file() -> Result<(), String> {
    let mut doc = NfsModule::parse(DEFAULT).map_err(|e| e.to_string())?;
    let model = Model {
        entries: vec![expect_export(
            "/srv/nfs4",
            &[("192.168.1.0/24", &["ro", "sync", "no_subtree_check"])],
        )],
    };
    let report = NfsModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert_eq!(report.changed_lines, 1);
    assert_eq!(report.added, 0);
    assert_eq!(report.removed, 1);
    assert_eq!(
        NfsModule::render(&doc),
        "# /etc/exports: NFS server export table.\n#\n# Each line: <export point> <client>(<option,...>) [<client>(<options>)...]\n# Apply changes with: exportfs -ra\n\n/srv/nfs4 192.168.1.0/24(ro,sync,no_subtree_check)\n"
    );
    Ok(())
}
