[package]
name = "detent-fuzz"
version = "0.0.1"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
detent-core = { path = "../crates/detent-core", features = ["fuzzing"] }
detent-module-hosts = { path = "../crates/modules/hosts" }

[profile.release]
debug = 1
