//! Generates the locale catalogue from the directories under `locales/`.
//!
//! A translator adds `locales/<tag>/` with `core.ftl`, `web.ftl` and `cli.ftl`;
//! this script finds it, checks the three files exist (the build fails with the
//! path if one is missing), compresses each file as raw DEFLATE into `$OUT_DIR`
//! and writes `$OUT_DIR/catalogue.rs`, which `src/lib.rs` includes. At run time
//! only the locales a process renders are inflated. `locale_scan.rs` holds the
//! scan rules, so the unit tests run the same code.
//!
//! The pseudo-locale (`qps-ploc`) is left out by rule. `web.ftl` is listed behind
//! `#[cfg(feature = "web")]`, so a build without that feature carries none of it.

#[path = "locale_scan.rs"]
mod locale_scan;

use miniz_oxide::deflate::compress_to_vec;
use miniz_oxide::inflate::decompress_to_vec_with_limit;
use std::error::Error;
use std::fmt::Write as _;
use std::path::PathBuf;
use std::{env, fs};

/// miniz level 10, the smallest output it makes. Build time is not a concern.
const LEVEL: u8 = 10;

/// The attribute line that keeps `web.ftl` out of a build without the `web` feature.
const WEB_GATE: &str = "#[cfg(feature = \"web\")]";

fn main() -> Result<(), Box<dyn Error>> {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let out = PathBuf::from(env::var("OUT_DIR")?);
    let locales = manifest.join("..").join("..").join("locales");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=locale_scan.rs");
    // A directory is watched recursively: a new locale or an edited file reruns this.
    println!("cargo:rerun-if-changed={}", locales.display());

    let mut statics = String::new();
    let mut table = String::from(
        "/// Every locale under `locales/`, sorted by tag. Generated by `build.rs`.\nstatic CATALOGUE: &[LocaleSource] = &[\n",
    );
    for (locale, tag) in locale_scan::scan(&locales)?.iter().enumerate() {
        fs::create_dir_all(out.join(tag))?;
        writeln!(
            table,
            "    LocaleSource {{\n        tag: {tag:?},\n        files: &["
        )?;
        for (index, file) in locale_scan::REQUIRED_FILES.into_iter().enumerate() {
            let text = fs::read(locales.join(tag).join(file))?;
            let packed = compress_to_vec(&text, LEVEL);
            let unpacked = decompress_to_vec_with_limit(&packed, text.len());
            if unpacked.as_ref().ok() != Some(&text) {
                return Err(format!("{tag}/{file} does not survive compression").into());
            }
            let blob = out.join(tag).join(format!("{file}.deflate"));
            fs::write(&blob, &packed)?;

            let name = format!("PACKED_{locale}_{index}");
            if file == "web.ftl" {
                writeln!(statics, "{WEB_GATE}")?;
                writeln!(table, "            {WEB_GATE}")?;
            }
            writeln!(
                statics,
                "static {name}: Packed = Packed::new({}, include_bytes!({:?}));",
                text.len(),
                blob.display().to_string(),
            )?;
            writeln!(table, "            &{name},")?;
        }
        writeln!(table, "        ],\n    }},")?;
    }
    table.push_str("];\n");
    fs::write(out.join("catalogue.rs"), format!("{statics}\n{table}"))?;
    Ok(())
}
