//! Generates the locale catalogue from the directories under `locales/`.
//!
//! A translator adds `locales/<tag>/` with `core.ftl`, `web.ftl` and `cli.ftl`;
//! this script finds it, checks the three files exist (the build fails with the
//! path if one is missing) and writes `$OUT_DIR/catalogue.rs`, which `src/lib.rs`
//! includes. `locale_scan.rs` holds the rules, so the unit tests run the same code.
//!
//! The pseudo-locale (`qps-ploc`) is left out by rule. `web.ftl` is listed behind
//! `#[cfg(feature = "web")]`, so a build without that feature carries none of it.

#[path = "locale_scan.rs"]
mod locale_scan;

use std::error::Error;
use std::fmt::Write as _;
use std::path::PathBuf;
use std::{env, fs};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let locales = manifest.join("..").join("..").join("locales");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=locale_scan.rs");
    // A directory is watched recursively: a new locale or an edited file reruns this.
    println!("cargo:rerun-if-changed={}", locales.display());

    let tags = locale_scan::scan(&locales)?;
    let mut code = String::from(
        "/// Every locale under `locales/`, sorted by tag. Generated by `build.rs`.\nstatic CATALOGUE: &[LocaleSource] = &[\n",
    );
    for tag in &tags {
        writeln!(
            code,
            "    LocaleSource {{\n        tag: {tag:?},\n        files: &["
        )?;
        for file in locale_scan::REQUIRED_FILES {
            let path = locales.join(tag).join(file);
            if file == "web.ftl" {
                writeln!(code, "            #[cfg(feature = \"web\")]")?;
            }
            writeln!(
                code,
                "            include_str!({:?}),",
                path.display().to_string()
            )?;
        }
        writeln!(code, "        ],\n    }},")?;
    }
    code.push_str("];\n");
    fs::write(
        PathBuf::from(env::var("OUT_DIR")?).join("catalogue.rs"),
        code,
    )?;
    Ok(())
}
