#!/usr/bin/env bash
#
# clean.sh - Free disk space taken by build, test, coverage and fuzz output.
#
# Usage:
#   scripts/clean.sh [OPTIONS]
#
# Options:
#   --real              Remove every git-ignored file (except the protected
#                       paths below) and the generated fuzz corpus: the tree
#                       as if just cloned. Default: the quick clean.
#   --dryrun            Print what would be removed; remove nothing.
#   --verbose, -v       Print each path and step-level progress.
#   -h, --help          Show this help message.
#
# Quick clean (default) removes what is large and rarely reused, and keeps
# the warm debug build and web/node_modules so the next build stays fast:
#   - incremental caches (target/*/incremental, target/*/*/incremental)
#   - coverage builds and data (target/llvm-cov-target, *.profraw, lcov files)
#   - release and cross-compiled output (target/release, target/<triple>)
#   - fuzz builds, crash files and generated (untracked) fuzz corpus
#   - web test reports (web/test-results, web/playwright-report, web/coverage)
#   - debug build files not touched for STALE_DAYS days (default 2)
#
# Real clean (--real) keeps tracked files and untracked files that are not
# ignored (your own work); it lists the latter so you can decide. It never
# removes these ignored paths: .sops/ (secrets) and .mcp.json* (local config).
#
# Environment:
#   STALE_DAYS          Age in days for the stale debug-file sweep (default 2).
#
# Requires: git, find, du.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
STALE_DAYS="${STALE_DAYS:-2}"

REAL=false
DRYRUN=false
VERBOSE=false

if [[ -n "${NO_COLOR:-}" ]]; then
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  NC=""
else
  RED=$'\033[0;31m'
  GREEN=$'\033[0;32m'
  YELLOW=$'\033[1;33m'
  BLUE=$'\033[0;34m'
  NC=$'\033[0m'
fi

log() {
  echo "${BLUE}[clean]${NC} $*"
}

log_verbose() {
  if [[ "${VERBOSE}" == true ]]; then
    echo "${BLUE}[clean][verbose]${NC} $*"
  fi
}

show_usage() {
  sed -n '2,33p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --real)
      REAL=true
      shift
      ;;
    --dryrun)
      DRYRUN=true
      shift
      ;;
    --verbose | -v)
      VERBOSE=true
      shift
      ;;
    -h | --help)
      show_usage
      exit 0
      ;;
    *)
      echo "${RED}error:${NC} unknown option: $1" >&2
      show_usage >&2
      exit 2
      ;;
  esac
done

if [[ ! "${STALE_DAYS}" =~ ^[0-9]+$ ]]; then
  echo "${RED}error:${NC} STALE_DAYS must be a whole number: ${STALE_DAYS}" >&2
  exit 2
fi

cd "${REPO_ROOT}"

# Paths are relative to the repository root and never leave it.
remove() {
  local path="$1"
  [[ -e "${path}" || -L "${path}" ]] || return 0
  case "${path}" in
    /* | ../* | */../* | .. | .)
      echo "${RED}error:${NC} refusing to remove ${path}" >&2
      exit 1
      ;;
  esac
  if [[ "${DRYRUN}" == true ]]; then
    echo "would remove ${path}"
  else
    log_verbose "removing ${path}"
    rm -rf -- "${path}"
  fi
}

# Untracked files under fuzz/corpus are generated by fuzz runs; the tracked
# seed corpus stays.
remove_generated_corpus() {
  local count=0
  while IFS= read -r -d '' path; do
    remove "${path}"
    count=$((count + 1))
  done < <(git ls-files -z --others --exclude-standard -- fuzz/corpus)
  log_verbose "generated fuzz corpus files: ${count}"
}

space_used() {
  du -sk . 2>/dev/null | cut -f1
}

before="$(space_used)"

if [[ "${REAL}" == true ]]; then
  log "real clean: every ignored file except .sops/ and .mcp.json*"
  while IFS= read -r line; do
    path="${line#Would remove }"
    path="${path%/}"
    case "${path}" in
      .sops | .sops/* | .mcp.json*)
        log_verbose "keeping protected ${path}"
        continue
        ;;
    esac
    remove "${path}"
  done < <(git clean -ndX)
  remove_generated_corpus
  leftover="$(git ls-files --others --exclude-standard)"
  if [[ -n "${leftover}" ]]; then
    echo "${YELLOW}note:${NC} untracked files that are not ignored were kept (your work?):"
    while IFS= read -r path; do
      echo "  ${path}"
    done <<<"${leftover}"
  fi
else
  log "quick clean: keeps the warm debug build and web/node_modules"
  shopt -s nullglob
  for dir in target/*/incremental target/*/*/incremental target/tmp/*; do
    remove "${dir}"
  done
  remove target/llvm-cov-target
  remove target/release
  for dir in target/*-*-*; do
    # target/<triple> holds cross-compiled output (for example
    # aarch64-unknown-linux-musl).
    [[ -d "${dir}" && "${dir}" != target/llvm-cov-target ]] && remove "${dir}"
  done
  remove fuzz/target
  remove fuzz/artifacts
  remove_generated_corpus
  for path in web/test-results web/playwright-report web/coverage coverage \
    lcov.info merged.info lcov-*.info *.profraw *.profdata; do
    remove "${path}"
  done
  shopt -u nullglob
  if [[ -d target/debug ]]; then
    log_verbose "sweeping target/debug files older than ${STALE_DAYS} days"
    if [[ "${DRYRUN}" == true ]]; then
      stale="$(find target/debug -type f -mtime "+${STALE_DAYS}" | wc -l | tr -d ' ')"
      echo "would remove ${stale} debug build files older than ${STALE_DAYS} days"
    else
      find target/debug -type f -mtime "+${STALE_DAYS}" -delete
      find target/debug -mindepth 1 -type d -empty -delete
    fi
  fi
fi

after="$(space_used)"
freed_mb=$(((before - after) / 1024))
if [[ "${DRYRUN}" == true ]]; then
  echo "${GREEN}dryrun${NC}: nothing removed"
else
  echo "${GREEN}done${NC}: freed about ${freed_mb} MiB"
fi
df -h . | tail -n 1
