//! Conformance suite for the `samba` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.

use detent_core::module::ConfigModule;
use detent_module_samba::{Entry, Model, SambaModule};
use proptest::prelude::Strategy;

/// The stock `smb.conf` sample: upstream's own `examples/smb.conf.default` at
/// the tracked tag, verbatim (tab-free 3-space indentation, `;`-commented
/// alternatives, and the `%m` macro in `log file`).
const DEFAULT: &str = include_str!("../../../../fixtures/samba/samba-4.24.7/smb-default");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/samba/edge/crlf");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/samba/edge/no-trailing-newline");
/// Tabs around `=`, 3-space indentation and a continuation line with no `=`.
const TABS: &str = include_str!("../../../../fixtures/samba/edge/tabs-and-spacing");
/// A `[`-opening line that never closes, a bare continuation, an empty key and
/// an empty header — all `Unknown` — next to lines the module does model.
const UNKNOWN: &str = include_str!("../../../../fixtures/samba/edge/unknown-directives");

/// Valid models: 0–10 entries, each either a `[section]` header (a name of
/// `[a-z0-9_-]`) or a `key = value` directive whose key is 1–3 words and whose
/// value carries none of the characters that would make `render_line` refuse
/// it — so every generated model survives `apply` and the invariants 3/4
/// checks are never vacuous.
fn model_strategy() -> impl Strategy<Value = Model> {
    let item = (
        proptest::bool::ANY,
        "[a-z0-9_-]{1,8}",
        "[a-z0-9_-]{1,8}( [a-z0-9_-]{1,8}){0,2}",
        "[a-z0-9_.%=/-]{0,12}",
    )
        .prop_map(|(header, section, key, value)| {
            if header {
                Entry {
                    section: Some(section),
                    key: String::new(),
                    value: String::new(),
                }
            } else {
                Entry {
                    section: None,
                    key,
                    value,
                }
            }
        });
    proptest::collection::vec(item, 0..=10).prop_map(|entries| Model { entries })
}

/// A model whose key carries `value`, for invariant 5.
fn key_probe(value: &str) -> Model {
    Model {
        entries: vec![Entry {
            section: None,
            key: value.to_owned(),
            value: "yes".to_owned(),
        }],
    }
}

/// A model whose value carries `value`, for invariant 5.
fn value_probe(value: &str) -> Model {
    Model {
        entries: vec![Entry {
            section: None,
            key: "log file".to_owned(),
            value: value.to_owned(),
        }],
    }
}

/// A model whose section name carries `value`, for invariant 5.
fn section_probe(value: &str) -> Model {
    Model {
        entries: vec![Entry {
            section: Some(value.to_owned()),
            key: String::new(),
            value: String::new(),
        }],
    }
}

detent_core::module_conformance!(
    SambaModule,
    fixtures = [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN],
    model_strategy = model_strategy(),
    injection_probes = [
        value_probe("a\nb"),
        value_probe("a\rb"),
        value_probe("a\0b"),
        key_probe("a\nb"),
        key_probe("a\rb"),
        key_probe("a\0b"),
        section_probe("a\nb"),
        section_probe("a\rb"),
        section_probe("a\0b"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEFAULT, CRLF, NO_NEWLINE, TABS, UNKNOWN] {
        let doc = SambaModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(SambaModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    SambaModule::parse(src)
        .ok()
        .and_then(|doc| SambaModule::to_model(&doc).ok())
        .unwrap_or_default()
}

/// Builds a directive entry.
fn expect(key: &str, value: &str) -> Entry {
    Entry {
        section: None,
        key: key.to_owned(),
        value: value.to_owned(),
    }
}

/// Builds a section-header entry.
fn expect_section(name: &str) -> Entry {
    Entry {
        section: Some(name.to_owned()),
        key: String::new(),
        value: String::new(),
    }
}

#[test]
fn default_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(DEFAULT),
        Model {
            entries: vec![
                expect_section("global"),
                expect("workgroup", "MYGROUP"),
                expect("server string", "Samba Server"),
                expect("server role", "standalone server"),
                // The `%m` macro rides along verbatim.
                expect("log file", "/usr/local/samba/var/log.%m"),
                expect("max log size", "50"),
                expect("dns proxy", "no"),
                expect_section("homes"),
                expect("comment", "Home Directories"),
                expect("browsable", "no"),
                expect("writable", "yes"),
                expect_section("printers"),
                expect("comment", "All Printers"),
                expect("path", "/usr/spool/samba"),
                expect("browsable", "no"),
                expect("guest ok", "no"),
                expect("writable", "no"),
                expect("printable", "yes"),
            ]
        }
    );
}

#[test]
fn crlf_fixture_keeps_its_terminators_and_parses_the_same() {
    assert_eq!(
        model_of(CRLF),
        Model {
            entries: vec![
                expect_section("global"),
                expect("workgroup", "SAMBA"),
                expect("log file", "/var/log/samba/log.%m"),
                expect_section("homes"),
                expect("writable", "yes"),
            ]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            entries: vec![
                expect_section("global"),
                expect("workgroup", "MYGROUP"),
                expect("max log size", "50"),
            ]
        }
    );
}

#[test]
fn tabs_fixture_keeps_alignment_and_drops_the_continuation() {
    assert_eq!(
        model_of(TABS),
        Model {
            entries: vec![
                expect_section("global"),
                expect("workgroup", "SAMBA"),
                expect("server services", "-smb2 +smb3"),
                expect("log file", "/var/log/samba/log.%m"),
                expect_section("homes"),
                expect("writable", "yes"),
            ]
        }
    );
}

#[test]
fn unknown_fixture_keeps_the_modeled_lines_and_drops_the_rest() {
    assert_eq!(
        model_of(UNKNOWN),
        Model {
            entries: vec![
                expect_section("global"),
                expect("workgroup", "SAMBA"),
                // The `include` line is modeled, `%m` macro and all; `[bad`,
                // the bare continuation, `= no-key`, `[]` and `%m` are not.
                expect("include", "/etc/samba/smb.conf.%m"),
            ]
        }
    );
}

/// `%` macros, `=`, `[`, `]` and `;` are ordinary data inside a value: they
/// must survive an apply/render round trip untouched, never be expanded and
/// never be mistaken for syntax.
#[test]
fn delimiters_and_macros_survive_in_values() -> Result<(), String> {
    let mut doc = SambaModule::parse("[global]\nlog file = /var/log.%m; [x] = y\n")
        .map_err(|e| e.to_string())?;
    let model = Model {
        entries: vec![
            expect_section("global"),
            expect("log file", "/var/log.%m; [x] = y"),
        ],
    };
    SambaModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert_eq!(
        SambaModule::render(&doc),
        "[global]\nlog file = /var/log.%m; [x] = y\n"
    );
    Ok(())
}

/// The one property the conformance macro cannot express for you — that an edit
/// actually reaches the file, and that everything around it is left alone. A
/// module can satisfy all six invariants by refusing every edit.
#[test]
fn an_edited_setting_reaches_the_rendered_file() -> Result<(), String> {
    let mut doc = SambaModule::parse(DEFAULT).map_err(|e| e.to_string())?;
    let mut model = SambaModule::to_model(&doc).map_err(|e| e.to_string())?;
    let Some(workgroup) = model.entries.get_mut(1) else {
        return Err("the default fixture must parse to at least two entries".to_owned());
    };
    workgroup.value = "DETECTED".to_owned();
    let report = SambaModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    assert_eq!(report.changed_lines, 1);
    assert_eq!(report.added, 0);
    assert_eq!(report.removed, 0);
    assert_eq!(
        SambaModule::render(&doc),
        DEFAULT.replace("   workgroup = MYGROUP", "workgroup = DETECTED")
    );
    Ok(())
}
