//! Conformance suite for the `hosts` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the model
//! strategy and the injection probes it needs, and asserts that each fixture parses
//! to the exact model it should.

use detent_core::module::ConfigModule;
use detent_module_hosts::{Entry, HostsModule, Model};
use proptest::prelude::{Strategy, any, prop_oneof};
use std::net::{IpAddr, Ipv4Addr};

/// Debian's stock `/etc/hosts`.
const DEBIAN: &str = include_str!("../../../../fixtures/hosts/glibc-2.42/debian-default.hosts");
/// Raspberry Pi OS, whose IPv6 block comes before the host's own name.
const RPI_OS: &str = include_str!("../../../../fixtures/hosts/glibc-2.42/rpi-os.hosts");
/// macOS 15, with `broadcasthost` and the `##` banner.
const MACOS: &str = include_str!("../../../../fixtures/hosts/macos-15/hosts");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/hosts/edge/crlf.hosts");
/// Hand-aligned columns and inline comments, including an empty one.
const TABS: &str = include_str!("../../../../fixtures/hosts/edge/tabs-and-inline-comments.hosts");
/// A zone id, a bare address, a bad address and a non-address: all unknown lines.
const ZONE: &str = include_str!("../../../../fixtures/hosts/edge/ipv6-zone-and-unknown.hosts");
/// A file whose last line has no terminator.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/hosts/edge/no-trailing-newline.hosts");

/// Builds an expected entry. A malformed address in a test yields `0.0.0.0`, which
/// fails the assertion that uses it rather than panicking.
fn expect_entry(ip: &str, hostnames: &[&str], comment: Option<&str>) -> Entry {
    Entry {
        ip: ip.parse().unwrap_or(IpAddr::V4(Ipv4Addr::UNSPECIFIED)),
        hostnames: hostnames.iter().map(|n| (*n).to_owned()).collect(),
        comment: comment.map(str::to_owned),
    }
}

/// Valid models: 0–20 entries, IPv4 or IPv6, 1–4 RFC 1123-shaped names, and an
/// optional already-trimmed comment.
fn model_strategy() -> impl Strategy<Value = Model> {
    let ip = prop_oneof![
        any::<[u8; 4]>().prop_map(IpAddr::from),
        any::<[u8; 16]>().prop_map(IpAddr::from),
    ];
    let entry = (
        ip,
        proptest::collection::vec("[a-z][a-z0-9-]{0,7}", 1..=4),
        proptest::option::of("[a-z0-9]{0,10}"),
    )
        .prop_map(|(ip, hostnames, comment)| Entry {
            ip,
            hostnames,
            comment,
        });
    proptest::collection::vec(entry, 0..=20).prop_map(|entries| Model { entries })
}

/// A model whose canonical name carries `value`, for invariant 5.
fn name_probe(value: &str) -> Model {
    Model {
        entries: vec![expect_entry("192.0.2.1", &[value], None)],
    }
}

/// A model whose comment carries `value`, for invariant 5.
fn comment_probe(value: &str) -> Model {
    Model {
        entries: vec![expect_entry("192.0.2.1", &["probe"], Some(value))],
    }
}

detent_core::module_conformance!(
    HostsModule,
    fixtures = [DEBIAN, RPI_OS, MACOS, CRLF, TABS, ZONE, NO_NEWLINE],
    model_strategy = model_strategy(),
    injection_probes = [
        name_probe("a\nb"),
        name_probe("a\rb"),
        name_probe("a\0b"),
        comment_probe("a\nb"),
        comment_probe("a\0b"),
    ],
);

/// Every fixture must render back byte for byte.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [DEBIAN, RPI_OS, MACOS, CRLF, TABS, ZONE, NO_NEWLINE] {
        let doc = HostsModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(HostsModule::render).ok(),
            Some(fixture.to_owned())
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so the
/// assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    HostsModule::parse(src)
        .ok()
        .and_then(|doc| HostsModule::to_model(&doc).ok())
        .unwrap_or_default()
}

#[test]
fn debian_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(DEBIAN),
        Model {
            entries: vec![
                expect_entry("127.0.0.1", &["localhost"], None),
                expect_entry("127.0.1.1", &["debian.example.org", "debian"], None),
                expect_entry("::1", &["ip6-localhost", "ip6-loopback"], None),
                expect_entry("fe00::0", &["ip6-localnet"], None),
                expect_entry("ff00::0", &["ip6-mcastprefix"], None),
                expect_entry("ff02::1", &["ip6-allnodes"], None),
                expect_entry("ff02::2", &["ip6-allrouters"], None),
            ]
        }
    );
}

#[test]
fn rpi_os_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(RPI_OS),
        Model {
            entries: vec![
                expect_entry("127.0.0.1", &["localhost"], None),
                expect_entry("::1", &["localhost", "ip6-localhost", "ip6-loopback"], None),
                expect_entry("ff02::1", &["ip6-allnodes"], None),
                expect_entry("ff02::2", &["ip6-allrouters"], None),
                expect_entry("127.0.1.1", &["raspberrypi"], None),
            ]
        }
    );
}

#[test]
fn macos_fixture_parses_to_its_entries() {
    assert_eq!(
        model_of(MACOS),
        Model {
            entries: vec![
                expect_entry("127.0.0.1", &["localhost"], None),
                expect_entry("255.255.255.255", &["broadcasthost"], None),
                expect_entry("::1", &["localhost"], None),
            ]
        }
    );
}

#[test]
fn crlf_fixture_keeps_its_terminators_and_comment() {
    assert_eq!(
        model_of(CRLF),
        Model {
            entries: vec![
                expect_entry("127.0.0.1", &["localhost"], None),
                expect_entry("::1", &["localhost"], None),
                expect_entry("192.168.1.10", &["nas.lan", "nas"], Some("storage")),
            ]
        }
    );
}

#[test]
fn inline_comments_are_trimmed_and_may_be_empty() {
    assert_eq!(
        model_of(TABS),
        Model {
            entries: vec![
                expect_entry("10.0.0.1", &["gw.lan", "gw"], Some("default gateway")),
                expect_entry(
                    "10.0.0.2",
                    &["ntp.lan", "ntp"],
                    Some("gps disciplined clock")
                ),
                expect_entry("10.0.0.3", &["printer.lan"], Some("")),
            ]
        }
    );
}

#[test]
fn zone_ids_and_malformed_lines_stay_unknown() {
    assert_eq!(
        model_of(ZONE),
        Model {
            entries: vec![expect_entry("::1", &["localhost"], None)]
        }
    );
}

#[test]
fn a_missing_trailing_newline_survives() {
    assert_eq!(
        model_of(NO_NEWLINE),
        Model {
            entries: vec![
                expect_entry("127.0.0.1", &["localhost"], None),
                expect_entry("192.168.1.20", &["sensor.lan"], None),
            ]
        }
    );
}
