//! Conformance suite for the `dhcp` module.
//!
//! The six invariants of `docs/PLAN.md` §2.3 are generated by
//! `detent_core::module_conformance!`; this file supplies the fixtures, the
//! model strategy and the injection probes it needs, and asserts that each
//! fixture parses to the exact model it should.
//!
//! # Fixture provenance (all verified live on 2026-09-17)
//!
//! * `fixtures/dhcp/dnsmasq-2.93/dnsmasq.conf.example` — verbatim from the
//!   dnsmasq `v2.93` tag (`https://thekelleys.org.uk/git/dnsmasq.git`, newest
//!   non-rc tag; `git ls-remote --tags` on that date listed `v2.93` above
//!   `v2.92`, with `v2.93rc*`/`v2.93test*` excluded). The stock sample is
//!   entirely blank and comment lines, so its exact model is empty — which is
//!   itself the assertion.
//! * `fixtures/dhcp/dnsmasq-2.93/trust-anchors.conf` — verbatim from the same
//!   tag: two `trust-anchor=…` lines, the real DNSSEC root KSK anchors.
//! * `fixtures/dhcp/dnsmasq-2.93/kea-dhcp4.conf` and `kea-dhcp6.conf` —
//!   verbatim from the ISC Kea `Kea-3.2.0` tag
//!   (`https://gitlab.isc.org/isc-projects/kea.git`, newest stable tag;
//!   `doc/examples/kea4/single-subnet.json` and
//!   `doc/examples/kea6/simple.json`).
//! * `fixtures/dhcp/edge/` — hand-made adversarial cases: CRLF, no trailing
//!   newline (dnsmasq and JSONC flavors), tabs and odd spacing around `=`,
//!   garbage lines that must stay `Unknown`, and a Kea file exercising every
//!   JSONC comment style.
//!
//! `module_conformance!` includes only tracked-version + edge fixtures; the
//! huge `dnsmasq.conf.example` is exercised through the explicit
//! round-trip and exact-model tests below instead of being re-run under
//! proptest.

use detent_core::module::ConfigModule;
use detent_module_dhcp::{DhcpModule, DnsmasqSetting, KeaConfig, KeaPool, KeaSubnet, Model};
use proptest::prelude::*;

/// The stock `dnsmasq.conf.example` shipped by dnsmasq 2.93: 689 lines, all
/// blank or comments, no directive at all.
const EXAMPLE: &str = include_str!("../../../../fixtures/dhcp/dnsmasq-2.93/dnsmasq.conf.example");
/// The real DNSSEC root anchors file from the same tag.
const TRUST: &str = include_str!("../../../../fixtures/dhcp/dnsmasq-2.93/trust-anchors.conf");
/// ISC Kea 3.2.0 `doc/examples/kea4/single-subnet.json`.
const KEA4: &str = include_str!("../../../../fixtures/dhcp/dnsmasq-2.93/kea-dhcp4.conf");
/// ISC Kea 3.2.0 `doc/examples/kea6/simple.json`.
const KEA6: &str = include_str!("../../../../fixtures/dhcp/dnsmasq-2.93/kea-dhcp6.conf");
/// Every line terminated with `\r\n`.
const CRLF: &str = include_str!("../../../../fixtures/dhcp/edge/crlf.dnsmasq");
/// Garbage that must stay `Unknown`: two-word lines, `=missing-key`, and the
/// `conf-file`/`conf-dir` includes the module never follows.
const GARBAGE: &str = include_str!("../../../../fixtures/dhcp/edge/garbage-lines.dnsmasq");
/// A file whose last line has no terminator, ending on a key/value pair.
const NO_NEWLINE: &str = include_str!("../../../../fixtures/dhcp/edge/no-trailing-newline.dnsmasq");
/// Tabs between key and `=`, hand-aligned columns.
const TABS: &str = include_str!("../../../../fixtures/dhcp/edge/tabs-and-spacing.dnsmasq");
/// A Kea `Dhcp6` file with no trailing newline.
const JSONC_NO_NEWLINE: &str =
    include_str!("../../../../fixtures/dhcp/edge/no-trailing-newline.jsonc");
/// A Kea `Dhcp4` file exercising every JSONC comment style.
const JSONC_COMMENTS: &str = include_str!("../../../../fixtures/dhcp/edge/jsonc-comments.conf");

/// `model_strategy` must generate **valid** models only — values this
/// module's `apply` would refuse make invariants 3 and 4 vacuous, because
/// their checks skip a model that `apply` rejects. The regexes stay inside
/// what both formats accept: no `\n`, `\r` or NUL anywhere (JSONC strings
/// reject them outright, dnsmasq values cannot carry them), dnsmasq keys that
/// parse back, and Kea strings that survive `apply`'s injection guard.
fn model_strategy() -> impl Strategy<Value = Model> {
    let flag = "[a-z][a-z0-9-]{1,19}".prop_map(|key| DnsmasqSetting { key, value: None });
    let pair =
        ("[a-z][a-z0-9-]{0,15}", "[a-z0-9][a-z0-9 .,/_:-]{0,19}").prop_map(|(key, value)| {
            DnsmasqSetting {
                key,
                value: Some(value),
            }
        });
    let dnsmasq = proptest::collection::vec(prop_oneof![flag, pair], 0..=10);
    prop_oneof![
        2 => dnsmasq.prop_map(|dnsmasq| Model {
            dnsmasq,
            ..Model::default()
        }),
        1 => kea_strategy().prop_map(|kea_v4| Model {
            kea_v4,
            ..Model::default()
        }),
        1 => kea_strategy().prop_map(|kea_v6| Model {
            kea_v6,
            ..Model::default()
        }),
    ]
}

/// A strategy for one Kea server's managed subset. Every string is JSONC- and
/// dnsmasq-safe by construction.
fn kea_strategy() -> impl Strategy<Value = KeaConfig> {
    (
        proptest::collection::vec("[a-z0-9]{1,10}", 0..=3),
        proptest::option::of(0u32..=100_000),
        proptest::collection::vec(subnet_strategy(), 0..=3),
    )
        .prop_map(|(interfaces, valid_lifetime, subnets)| KeaConfig {
            interfaces,
            valid_lifetime,
            subnets,
        })
}

/// A strategy for one Kea subnet; `routers` and `domain-name-servers` are one
/// model string per `option-data` entry, so any printable token works.
fn subnet_strategy() -> impl Strategy<Value = KeaSubnet> {
    (
        any::<u32>(),
        "[a-z0-9 .,/_-]{1,20}",
        proptest::collection::vec("[a-z0-9 .,/_-]{1,20}", 0..=2),
        proptest::collection::vec("[a-z0-9 .,/_-]{1,20}", 0..=2),
        proptest::collection::vec("[a-z0-9 .,/_-]{1,20}", 0..=2),
    )
        .prop_map(|(id, subnet, pools, routers, domain_servers)| KeaSubnet {
            id,
            subnet,
            pools: pools.into_iter().map(|pool| KeaPool { pool }).collect(),
            routers,
            domain_servers,
        })
}

/// A dnsmasq model whose key carries `value`, for invariant 5.
fn key_probe(value: &str) -> Model {
    Model {
        dnsmasq: vec![DnsmasqSetting {
            key: value.to_owned(),
            value: None,
        }],
        ..Model::default()
    }
}

/// A dnsmasq model whose value carries `value`, for invariant 5.
fn value_probe(value: &str) -> Model {
    Model {
        dnsmasq: vec![DnsmasqSetting {
            key: "domain-name".to_owned(),
            value: Some(value.to_owned()),
        }],
        ..Model::default()
    }
}

/// A model whose `interfaces` entry carries `value`, for invariant 5.
fn interfaces_probe(value: &str) -> Model {
    Model {
        kea_v4: KeaConfig {
            interfaces: vec![value.to_owned()],
            ..KeaConfig::default()
        },
        ..Model::default()
    }
}

/// A model whose `subnet` string carries `value`, for invariant 5.
fn subnet_probe(value: &str) -> Model {
    Model {
        kea_v4: KeaConfig {
            subnets: vec![KeaSubnet {
                id: 1,
                subnet: value.to_owned(),
                ..KeaSubnet::default()
            }],
            ..KeaConfig::default()
        },
        ..Model::default()
    }
}

/// A model whose pool string carries `value`, for invariant 5.
fn pool_probe(value: &str) -> Model {
    Model {
        kea_v4: KeaConfig {
            subnets: vec![KeaSubnet {
                id: 1,
                subnet: "192.0.2.0/24".to_owned(),
                pools: vec![KeaPool {
                    pool: value.to_owned(),
                }],
                ..KeaSubnet::default()
            }],
            ..KeaConfig::default()
        },
        ..Model::default()
    }
}

/// A model whose routers entry carries `value`, for invariant 5.
fn routers_probe(value: &str) -> Model {
    Model {
        kea_v4: KeaConfig {
            subnets: vec![KeaSubnet {
                id: 1,
                subnet: "192.0.2.0/24".to_owned(),
                routers: vec![value.to_owned()],
                ..KeaSubnet::default()
            }],
            ..KeaConfig::default()
        },
        ..Model::default()
    }
}

/// A model whose domain-name-servers entry carries `value`, for invariant 5.
fn domain_probe(value: &str) -> Model {
    Model {
        kea_v4: KeaConfig {
            subnets: vec![KeaSubnet {
                id: 1,
                subnet: "192.0.2.0/24".to_owned(),
                domain_servers: vec![value.to_owned()],
                ..KeaSubnet::default()
            }],
            ..KeaConfig::default()
        },
        ..Model::default()
    }
}

// One probe per field that reaches the rendered file, plus NUL and the
// dnsmasq delimiters (`#` opens a comment, `=` would change the key/value
// split). A `#`-starting *value* is deliberately absent: `key=#v` still
// round-trips, because dnsmasq has no inline comments — only a line that
// *starts* with `#` is a comment line.
detent_core::module_conformance!(
    DhcpModule,
    fixtures = [
        TRUST,
        KEA4,
        KEA6,
        CRLF,
        GARBAGE,
        NO_NEWLINE,
        TABS,
        JSONC_NO_NEWLINE,
        JSONC_COMMENTS
    ],
    model_strategy = model_strategy(),
    injection_probes = [
        key_probe("a\nb"),
        key_probe("a\rb"),
        key_probe("a\0b"),
        key_probe("a b"),
        key_probe("a=b"),
        key_probe("#domain-needed"),
        key_probe(""),
        value_probe("a\nb"),
        value_probe("a\rb"),
        value_probe("a\0b"),
        interfaces_probe("e\n0"),
        interfaces_probe("e\0"),
        subnet_probe("1\n24"),
        pool_probe("a\nb"),
        routers_probe("r\n1"),
        domain_probe("d\nrb"),
    ],
);

/// Every fixture must render back byte for byte — the big commented example
/// included.
#[test]
fn fixtures_round_trip_losslessly() {
    for fixture in [
        EXAMPLE,
        TRUST,
        KEA4,
        KEA6,
        CRLF,
        GARBAGE,
        NO_NEWLINE,
        TABS,
        JSONC_NO_NEWLINE,
        JSONC_COMMENTS,
    ] {
        let doc = DhcpModule::parse(fixture);
        assert_eq!(
            doc.as_ref().map(DhcpModule::render).ok(),
            Some(fixture.to_owned()),
            "fixture did not round-trip losslessly"
        );
    }
}

/// Parses `src` into a model, or an empty model if parsing somehow failed, so
/// the assertion in the caller reports the difference instead of panicking.
fn model_of(src: &str) -> Model {
    DhcpModule::parse(src)
        .ok()
        .and_then(|doc| DhcpModule::to_model(&doc).ok())
        .unwrap_or_default()
}

/// One test per fixture, asserting the exact model. A fixture that only
/// round-trips proves losslessness but not that the parser understood it.
#[test]
fn example_fixture_is_all_comments() {
    assert_eq!(model_of(EXAMPLE), Model::default());
}

#[test]
fn trust_fixture_parses_to_its_anchors() {
    let model = model_of(TRUST);
    assert_eq!(model.dnsmasq.len(), 2);
    for setting in &model.dnsmasq {
        assert_eq!(setting.key, "trust-anchor");
        assert!(
            setting
                .value
                .as_deref()
                .is_some_and(|v| v.starts_with(".,"))
        );
    }
}

#[test]
fn kea4_fixture_parses_to_its_model() {
    let model = model_of(KEA4);
    assert_eq!(model.dnsmasq, Vec::new());
    assert_eq!(model.kea_v4.interfaces, vec!["eth0".to_owned()]);
    assert_eq!(model.kea_v4.valid_lifetime, Some(4000));
    assert_eq!(
        model.kea_v4.subnets,
        vec![KeaSubnet {
            id: 1,
            subnet: "192.0.2.0/24".to_owned(),
            pools: vec![KeaPool {
                pool: "192.0.2.1 - 192.0.2.200".to_owned(),
            }],
            routers: Vec::new(),
            domain_servers: Vec::new(),
        }]
    );
    assert_eq!(model.kea_v6, KeaConfig::default());
}

#[test]
fn kea6_fixture_parses_to_its_model() {
    let model = model_of(KEA6);
    assert_eq!(model.kea_v4, KeaConfig::default());
    assert_eq!(model.kea_v6.interfaces, vec!["eth0".to_owned()]);
    assert_eq!(model.kea_v6.valid_lifetime, Some(4000));
    assert_eq!(
        model.kea_v6.subnets,
        vec![KeaSubnet {
            id: 1,
            subnet: "2001:db8:1::/64".to_owned(),
            pools: vec![KeaPool {
                pool: "2001:db8:1::/80".to_owned(),
            }],
            routers: Vec::new(),
            domain_servers: Vec::new(),
        }]
    );
}

#[test]
fn edge_fixtures_parse_to_their_exact_models() {
    // CRLF: every line a flag or pair, all recognized.
    let model = model_of(CRLF);
    assert_eq!(
        model.dnsmasq,
        vec![
            DnsmasqSetting {
                key: "domain-needed".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "bogus-priv".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "dhcp-leasefile".to_owned(),
                value: Some("/var/lib/dnsmasq/dnsmasq.leases".to_owned()),
            },
        ]
    );
    // Garbage: `Unknown` lines stay out of the model; recognized lines stay
    // in; `conf-file`/`conf-dir` are refused on purpose.
    let model = model_of(GARBAGE);
    assert_eq!(
        model.dnsmasq,
        vec![
            DnsmasqSetting {
                key: "domain-needed".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "dhcp-authoritative".to_owned(),
                value: None,
            },
        ]
    );
    // Tabs and spacing around `=` are trimmed by the parser.
    let model = model_of(TABS);
    assert_eq!(
        model.dnsmasq,
        vec![
            DnsmasqSetting {
                key: "domain-needed".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "interface".to_owned(),
                value: Some("eth0".to_owned()),
            },
            DnsmasqSetting {
                key: "dhcp-leasefile".to_owned(),
                value: Some("/var/lib/dnsmasq/dnsmasq.leases".to_owned()),
            },
            DnsmasqSetting {
                key: "bind-interfaces".to_owned(),
                value: None,
            },
        ]
    );
    // The JSONC flavors project to their managed subsets.
    let model = model_of(JSONC_NO_NEWLINE);
    assert_eq!(model.kea_v6.interfaces, vec!["eth0".to_owned()]);
    assert_eq!(model.kea_v6.valid_lifetime, Some(4000));
    assert_eq!(model.kea_v6.subnets.len(), 1);
    let model = model_of(JSONC_COMMENTS);
    assert_eq!(model.kea_v4.interfaces, vec!["eth0".to_owned()]);
    assert_eq!(model.kea_v4.valid_lifetime, Some(3600));
    assert_eq!(model.kea_v4.subnets.len(), 1);
    // The last dnsmasq line has no terminator but still parses.
    let model = model_of(NO_NEWLINE);
    assert_eq!(
        model.dnsmasq.first().map(|s| s.key.as_str()),
        Some("domain-needed")
    );
    assert_eq!(
        model.dnsmasq.get(1).and_then(|s| s.value.as_deref()),
        Some("lo")
    );
}

/// An edit must actually reach the file: the Kea v4 fixture's interface and
/// lifetime change, and the rendered document reflects it.
#[test]
fn an_edited_value_reaches_the_rendered_file() -> Result<(), String> {
    let mut doc = DhcpModule::parse(KEA4).map_err(|e| e.to_string())?;
    let mut model = model_of(KEA4);
    if let Some(first) = model.kea_v4.interfaces.first_mut() {
        *first = "eth1".to_owned();
    }
    model.kea_v4.valid_lifetime = Some(3600);
    DhcpModule::apply(&mut doc, &model).map_err(|e| e.to_string())?;
    let rendered = DhcpModule::render(&doc);
    assert!(rendered.contains("eth1"), "{rendered}");
    assert!(rendered.contains("3600"));
    assert_eq!(DhcpModule::to_model(&doc).ok(), Some(model));
    Ok(())
}

/// CRLF and no-trailing-newline must survive an actual edit, not just a
/// no-op round-trip.
#[test]
fn edge_line_endings_survive_edits() -> Result<(), String> {
    // Rewrite every CRLF fixture setting through the model; the trailing
    // `\r\n` of the last rewritten line must survive.
    let mut crlf_doc = DhcpModule::parse(CRLF).map_err(|e| e.to_string())?;
    let crlf_model = Model {
        dnsmasq: vec![
            DnsmasqSetting {
                key: "domain-needed".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "bogus-priv".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "dhcp-leasefile".to_owned(),
                value: Some("/tmp/leases".to_owned()),
            },
        ],
        ..Model::default()
    };
    DhcpModule::apply(&mut crlf_doc, &crlf_model).map_err(|e| e.to_string())?;
    let rendered = DhcpModule::render(&crlf_doc);
    assert!(rendered.ends_with("\r\n"), "{rendered:?}");
    assert!(rendered.contains("/tmp/leases"));

    // The no-trailing-newline file must still not gain a terminator.
    let mut nl_doc = DhcpModule::parse(NO_NEWLINE).map_err(|e| e.to_string())?;
    let nl_model = Model {
        dnsmasq: vec![
            DnsmasqSetting {
                key: "domain-needed".to_owned(),
                value: None,
            },
            DnsmasqSetting {
                key: "interface".to_owned(),
                value: Some("eth0".to_owned()),
            },
        ],
        ..Model::default()
    };
    DhcpModule::apply(&mut nl_doc, &nl_model).map_err(|e| e.to_string())?;
    let rendered = DhcpModule::render(&nl_doc);
    assert_eq!(
        rendered,
        "# hand-made edge fixture: the last line has no terminator\ndomain-needed\ninterface=eth0"
    );
    Ok(())
}
